import type { Copy } from "./types";

const budgets = {
  portraits: [
    { value: "lt-175", label: "Menos de 175 €" },
    { value: "175-300", label: "175–300 €" },
    { value: "300-500", label: "300–500 €" },
    { value: "500+", label: "500 € o más" },
  ],
  weddings: [
    { value: "lt-650", label: "Menos de 650 €" },
    { value: "650-1100", label: "650–1.100 €" },
    { value: "1100-1650", label: "1.100–1.650 €" },
    { value: "1650+", label: "1.650 € o más" },
  ],
  retreats: [
    { value: "lt-400", label: "Menos de 400 €" },
    { value: "400-1000", label: "400–1.000 €" },
    { value: "1000-2000", label: "1.000–2.000 €" },
    { value: "2000+", label: "2.000 € o más" },
  ],
  artists: [
    { value: "lt-110", label: "Menos de 110 €" },
    { value: "110-300", label: "110–300 €" },
    { value: "300-600", label: "300–600 €" },
    { value: "600+", label: "600 € o más" },
  ],
  places: [
    { value: "lt-475", label: "Menos de 475 €" },
    { value: "475-900", label: "475–900 €" },
    { value: "900+", label: "900 € o más" },
  ],
  other: [
    { value: "lt-175", label: "Menos de 175 €" },
    { value: "175-600", label: "175–600 €" },
    { value: "600-1500", label: "600–1.500 €" },
    { value: "1500+", label: "1.500 € o más" },
  ],
};

export const es: Copy = {
  meta: {
    home: {
      title: "Oracle of Freedom · Foto y vídeo, Algarve y Lisboa",
      description:
        "Foto y vídeo para espíritus libres, del Algarve a Lisboa. Bodas, retiros, festivales y trabajos comerciales viajan más lejos: el resto de Portugal, Europa y más allá.",
      keywords: "fotógrafa Algarve y Lisboa; fotógrafa Algarve; fotógrafa Lisboa; fotógrafa boho Portugal",
    },
    about: {
      title: "Sobre Agota · Fotógrafa del Algarve a Lisboa",
      description:
        "Conoce a Agota Urbikaite. Cada sesión cubre del Algarve a Lisboa. Bodas, retiros, festivales y trabajos comerciales pueden ir más lejos.",
      keywords: "Agota Urbikaite fotógrafa; fotógrafa Algarve y Lisboa; fotógrafa natural Portugal",
    },
    people: {
      title: "Personas · Retratos y bodas íntimas boho",
      description:
        "Retratos y bodas íntimas boho del Algarve a Lisboa, costa incluida. Las bodas pueden viajar más lejos. Sesiones desde 175 €.",
      keywords: "fotógrafa de parejas Algarve; fotógrafa de bodas Lisboa; boda boho Portugal",
    },
    portraits: {
      title: "Sesión de pareja y preboda · Algarve y Lisboa",
      description:
        "Sesiones de retrato para una persona, una pareja, una familia o amigos, del Algarve a Lisboa. Naturales, sin poses rígidas. Desde 175 €.",
      keywords: "fotógrafa de parejas Algarve; preboda Lisboa; sesión de fotos Algarve; pedida de mano Lisboa",
    },
    elopements: {
      title: "Fotógrafa de elopements boho · Algarve y Lisboa",
      description:
        "Elopements íntimos del Algarve a Lisboa, y más lejos por Portugal, Europa y más allá. Círculos pequeños, hasta unas 30 personas. Desde 690 €.",
      keywords: "fotógrafa elopement Algarve; elopement Lisboa; boda boho Portugal; boda íntima fotógrafa",
    },
    experiences: {
      title: "Experiencias · Retiros, festivales y artistas",
      description:
        "Retiros, festivales, DJs y artistas de fuego. Con base del Algarve a Lisboa, y viajando más lejos para los encuentros grandes.",
      keywords: "fotógrafa de retiros Algarve; fotógrafa de festivales Lisboa; fotógrafa de retiros Portugal",
    },
    retreats: {
      title: "Fotógrafa de retiros · Algarve, Lisboa y más allá",
      description:
        "Foto y vídeo de retiros del Algarve a Lisboa, y más lejos por Portugal y Europa. Con consentimiento y licencia comercial. Desde 400 €/día.",
      keywords: "fotógrafa retiros Algarve; fotógrafa retiros Lisboa; fotógrafa retiros de yoga; videógrafa retiros",
    },
    festivals: {
      title: "Fotógrafa de festivales y DJs · Algarve y Lisboa",
      description:
        "Fotos de prensa, clips de sets, retratos de fuego y videoclips. Del Algarve a Lisboa, y de viaje para festivales y trabajos comerciales. Desde 190 €.",
      keywords: "fotógrafa de festivales Algarve; fotógrafo DJ Lisboa; fotógrafa fire show; videoclip Portugal",
    },
    places: {
      title: "Fotógrafa de eco-alojamientos · Algarve y Lisboa",
      description:
        "Fotos y reels para eco-quintas, surf houses y alojamientos boutique del Algarve a Lisboa. Los trabajos comerciales pueden viajar más lejos. Desde 475 €.",
      keywords: "fotógrafa hoteles Algarve; surf house Lisboa; fotógrafa Airbnb Algarve; fotos para casa rural",
    },
    portfolio: {
      title: "Portfolio · Oracle of Freedom",
      description: "Momentos reales de las almas indómitas. Retratos, encuentros, festivales, fuego, DJs y vídeo.",
      keywords: "portfolio Agota Urbikaite; fotógrafa boho Portugal",
    },
    journal: {
      title: "Journal · Guías para espíritus libres",
      description:
        "Guías para un elopement boho en Portugal, fotografiar un retiro para llenar el siguiente, y sesiones de pareja en Ericeira y Sintra.",
      keywords: "elopement boho Algarve; sesión de pareja Lisboa; fotografía de retiros",
    },
    inquire: {
      title: "Contacto · Oracle of Freedom",
      description: "Cuéntame tu historia: fecha, lugar y sueño. Respondo en 48 horas. También por WhatsApp o email.",
      keywords: "contactar fotógrafa Algarve; contactar fotógrafa Lisboa",
    },
    book: {
      title: "Reserva una llamada · Oracle of Freedom",
      description: "Elige una hora para conocer a la fotógrafa y videógrafa Agota Urbikaite.",
      keywords: "reservar Agota Urbikaite; reservar fotógrafa Algarve; reservar fotógrafa Lisboa",
    },
    privacy: {
      title: "Privacidad · Oracle of Freedom",
      description: "Cómo Oracle of Freedom usa los datos del formulario, las cookies y los vídeos incrustados. Un aviso breve de RGPD.",
      keywords: "privacidad Oracle of Freedom; RGPD",
    },
  },
  a11y: {
    skip: "Saltar al contenido",
    menu: "Abrir menú",
    closeMenu: "Cerrar menú",
    home: "Oracle of Freedom, inicio",
    openPhoto: "Abrir foto",
    close: "Cerrar",
    previous: "Anterior",
    next: "Siguiente",
    photoPlaceholder: "Marcador en baja resolución — se sustituirá",
    language: "Idioma",
  },
  nav: {
    people: "Personas",
    experiences: "Experiencias",
    places: "Lugares",
    portfolio: "Portfolio",
    about: "Sobre mí",
    journal: "Journal",
    book: "Reservar",
    inquire: "Contacto",
  },
  footer: {
    blurb:
      "Foto y vídeo por Agota Urbikaite, del Algarve a Lisboa. Bodas, retiros, festivales y trabajos comerciales viajan más lejos.",
    privacy: "Privacidad",
    rights: "Todos los derechos reservados.",
  },
  whatsapp: {
    button: "Escríbeme",
    general: "¡Hola Agota! Te encontré en oracleoffreedom.com y me encantaría hablar contigo 🌿",
    portraits: "¡Hola Agota! Me gustaría una sesión de retrato hacia [fecha] en [lugar]. Te cuento quién viene y qué me gustaría:",
    elopements: "¡Hola Agota! Soñamos con un elopement boho íntimo hacia [fecha] 💛",
    retreats: "¡Hola Agota! Organizo un retiro el [fechas] y me encantaría tu cobertura",
    festivals: "¡Hola Agota! Soy DJ/artista y necesito contenido para…",
    places: "¡Hola Agota! Llevo [alojamiento] y me gustaría hablar de contenido",
  },
  common: {
    explore: "Descubrir",
    viewPortfolio: "Ver portfolio",
    readGuides: "Leer las guías",
    meet: "Conóceme",
    from: "Desde",
    priceNote: "Precios desde, en EUR y sin IVA. Bodas, alojamientos y festivales se confirman con un presupuesto.",
    offer: "Oferta",
    saveSeparately: "Ahorras {amount} frente a reservarlos por separado",
    placeholderTitle: "Pendiente — no es un testimonio publicado",
    placeholderBody: "Las citas reales sustituirán esto cuando Agota tenga permiso para compartirlas. Aquí no hay textos inventados.",
    comingSoon: "Próximamente",
    mostLoved: "la favorita",
    closingTitle: "Tu historia, sentida desde dentro.",
    closingBody:
      "Cuéntame qué sueñas: un atardecer en los acantilados, una semana de breathwork entre colinas, una noche de fuego y tambores. Te diré con sinceridad cómo puedo ayudarte.",
    closingPrimary: "Consultar disponibilidad",
    closingSecondary: "o escríbeme por WhatsApp",
    checkAvailability: "Consultar disponibilidad",
    seeWork: "Ver el trabajo",
  },
  cookies: {
    text: "Este sitio guarda una preferencia de idioma y, solo si aceptas, carga vídeos de Instagram y YouTube. Sin cookies de marketing.",
    accept: "Aceptar vídeos",
    essential: "Solo lo esencial",
    privacy: "Aviso de privacidad",
  },
  home: {
    title: "Para espíritus libres, encuentros sagrados y lugares con alma.",
    dek: "Foto y vídeo para espíritus libres: parejas enamoradas, encuentros sagrados, almas festivaleras y los lugares que los acogen. Cada sesión del Algarve a Lisboa; bodas, retiros, festivales y trabajos comerciales, más lejos.",
    manifesto:
      "No miro desde fuera. Bailo al borde del fuego, entro al mar contigo, me siento en el círculo. Ahí viven los momentos reales, y ahí está mi cámara.",
    doorsTitle: "Tres puertas",
    peopleTitle: "Personas",
    peopleBody: "Retratos, sesiones de preboda y bodas íntimas boho y elopements. Luz dorada, pelo salado, amor de verdad.",
    peoplePrice: "Sesiones desde {session} · Elopements desde {elopement}",
    experiencesTitle: "Experiencias",
    experiencesBody: "Retiros, encuentros, festivales, DJs, artistas de fuego y flow, videoclips. La energía del momento, capturada desde dentro.",
    experiencesPrice: "Cobertura de retiros desde {retreat}/día",
    placesTitle: "Lugares",
    placesBody: "Eco-quintas, surf houses y alojamientos boutique conscientes. Imágenes y reels que hacen sentir tu lugar antes de llegar.",
    placesPrice: "Jornadas de contenido desde {places}",
    howTitle: "Cómo trabajo",
    how: [
      { title: "Me vuelvo parte de ello.", body: "Sin poses rígidas ni presencia invasiva. Me muevo con el flujo para que olvides la cámara." },
      { title: "Foto y vídeo, una sola persona.", body: "Una mirada y un corazón: menos equipo, más intimidad." },
      { title: "Consentimiento, siempre.", body: "En círculos, ceremonias y festivales, nadie aparece ni se comparte sin su sí." },
    ],
    featuredTitle: "Trabajo destacado",
    wordsTitle: "Palabras bonitas",
    about:
      "Hola, soy Agota. Llevo más de 10 años fotografiando y grabando los momentos en los que nadie posa, capturando la esencia y la magia de los eventos, las comunidades y las almas indómitas.",
    journalTitle: "Journal",
    journalDek: "Guías para soñadores y para quien organiza.",
    closingTitle: "Cuéntame tu historia.",
    follow: "Sígueme en @oracle.of.freedom",
    igNote: "Una rejilla quieta del portfolio. La que vive está en Instagram.",
  },
  about: {
    title: "Hola, soy Agota.",
    paragraphs: [
      "Llevo más de 10 años trabajando con la fotografía y el vídeo, tanto de forma profesional como en proyectos de pasión. Me especializo en capturar momentos espontáneos de verdad y en dar vida a la magia de un evento o de una comunidad, en imágenes y en montajes de vídeo.",
      "Mi estilo es fluido y orgánico: un equilibrio delicado entre energías opuestas, la acción y la calma. No se trata solo de capturar el momento, sino de estar en él; no solo de estar cerca de la acción, sino de formar parte de ella. Eso es lo que da profundidad a mi trabajo, y donde se capturan los momentos más dulces y genuinos, aquellos en los que quien mira pasa a formar parte de todo.",
      "Me atraen las personas y los lugares con espíritu libre: encuentros en la jungla, ceremonias junto al río, votos descalzos en la playa, DJs perdidos en su set, casas ecológicas construidas con amor. Y esa es la magia que quiero capturar.",
    ],
    promise: "Oracle of Freedom es mi promesa: verte tal como eres y dejar ese momento en libertad.",
    valuesTitle: "En lo que creo",
    values: [
      { title: "Presencia", body: "Me entrego por completo para que tú también puedas hacerlo." },
      { title: "Consentimiento", body: "Tus momentos son tuyos. Pregunto, escucho y respeto los espacios sin cámara." },
      { title: "Libertad", body: "Sin guiones ni poses forzadas; solo una guía suave cuando la quieras." },
      { title: "Comunidad", body: "Formo parte de los círculos que fotografío y los trato con cuidado." },
    ],
    facts: "Más de 10 años en foto y vídeo · Foto y vídeo · Idiomas: inglés y lituano con fluidez, y español de conversación",
    bts: "PENDIENTE — fotos de Agota trabajando, aún por hacer. Este bloque se queda vacío hasta que existan.",
    closingTitle: "Creemos algo real juntos.",
  },
  people: {
    title: "Personas",
    dek: "Retratos, historias de amor y bodas íntimas boho, fotografiadas con calidez, libertad y cero rigidez.",
    portraitsTitle: "Sesiones de retrato",
    portraitsBody: "Una sesión para personas, parejas, prebodas, familias y amigos. El precio de partida se ajusta a lo que quieres.",
    portraitsPrice: "Desde {price}",
    weddingsTitle: "Bodas boho y elopements",
    weddingsBody: "Votos descalzos, un pequeño círculo de seres queridos, ceremonias que se parecen a vosotros.",
    weddingsPrice: "Desde {price}",
    wordsTitle: "Palabras bonitas",
  },
  experiences: {
    title: "Experiencias",
    dek: "Retiros, encuentros, festivales, DJs, artistas de fuego y flow, y videoclips, fotografiados y grabados desde dentro del círculo.",
    retreatsTitle: "Retiros y encuentros",
    retreatsBody: "Fotos y reels que te ayudan a llenar tu próximo retiro.",
    retreatsPrice: "Desde {price}/día",
    festivalsTitle: "Festivales, DJs y artistas",
    festivalsBody: "Fotos de prensa, clips de sets, fire shows, showreels y videoclips.",
    festivalsPrice: "Desde {price}",
    consentTitle: "Consentimiento, siempre.",
    consent:
      "Los espacios sagrados merecen respeto. Acordamos los momentos sin cámara, puedo usar pulseras o señales para quien no quiera aparecer, y nada se publica sin aprobación.",
  },
  portraits: {
    eyebrow: "Sesiones de retrato",
    title: "Para quienes van descalzos, arden y viven libres.",
    subtitle: "Sesiones de retrato, del Algarve a Lisboa",
    dek: "Una sesión para ti, para dos o para la gente que quieres. Personas, parejas, preboda, familias y amigos.",
    cta: "Reservar sesión",
    personalizeCta: "Personaliza tu sesión",
    personalizeWhatsapp: "o escríbeme por WhatsApp",
    inquiry: "portraits",
    whoTitle: "Para quién",
    who: [
      "Una persona, una pareja, una preboda, una familia o un grupo de amigos",
      "Pedidas sorpresa, aniversarios y vacaciones juntos",
      "Quien quiera fotografías naturales, sin poses rígidas",
      "Profesores de yoga, terapeutas, facilitadores, músicos y artistas que necesitan imágenes con alma para su marca",
    ],
    packagesTitle: "Sesiones",
    filmsTitle: "Vídeo",
    combosTitle: "Foto + vídeo",
    addonsTitle: "Entrega exprés",
    packages: {
      "portrait-sessions": {
        name: "Sesiones de retrato",
        items: [
          "Personas, parejas, preboda, familias, amigos: cualquier grupo",
          "Empieza en una hora. La duración, las fotos editadas, los lugares y cuántas personas dan forma al precio final",
          "Guía suave, sin poses rígidas",
          "Una galería privada en {artistWeeks}, lista para descargar y compartir",
        ],
      },
      "couples-film": {
        name: "Película de pareja",
        items: ["Una película corta de la sesión, de unos 60–90 segundos", "Un corte vertical para stories", "Entrega en {artistFilmWeeks}"],
      },
      "couples-combo": {
        name: "Sesión de retrato + vídeo",
        items: ["La sesión de retrato y la película corta", "Una sola persona, una tarde", "Fotos y vídeo en {artistFilmWeeks}: foto+vídeo sigue el plazo del vídeo"],
      },
      "portrait-film-express": {
        name: "Vídeo exprés",
        items: [
          "Acelera la película de pareja",
          "Lista en {expressFilm} en lugar de {artistFilmWeeks}",
          "Un extra de pago: añádelo al reservar",
        ],
      },
      "portrait-combo-express": {
        name: "Foto + vídeo exprés",
        items: [
          "Acelera la sesión de retrato y la película juntas",
          "Las dos en {expressFilm} en lugar de {artistFilmWeeks}",
          "Las fotografías solas pueden ir exprés en {expressPhoto}",
        ],
      },
    },
    travelNote:
      "El desplazamiento está incluido en cada sesión, del Algarve a Lisboa, con la costa de por medio. Bodas, retiros, festivales y trabajos comerciales pueden ir más lejos — el resto de Portugal, Europa y más allá — con el viaje a coste real.",
    whereTitle: "Dónde podemos hacer la sesión",
    where:
      "Todo el Algarve y la costa hasta Lisboa: el sur, la Costa Vicentina, el litoral del Alentejo, Comporta, Arrábida y la ciudad. Ericeira y Sintra quedan justo al norte de Lisboa: dímelo si ese es el plan. Para una boda, un retiro, un festival o un trabajo comercial, el resto de Portugal, Europa y más allá están abiertos.",
    processTitle: "Cómo funciona",
    process: [
      { title: "Escríbeme", body: "Envía el formulario o un WhatsApp con tu idea de fecha y lo que sueñas." },
      { title: "Planificamos", body: "Te sugiero lugares, horario para la mejor luz y qué ponerte." },
      { title: "La sesión", body: "Relajada, divertida, real. Te guío cuando lo necesitas y desaparezco cuando no." },
      { title: "Revívelo", body: "Llega tu galería privada en {artistWeeks}, lista para descargar, compartir e imprimir. El vídeo y las colecciones foto+vídeo siguen el plazo del vídeo, {artistFilmWeeks}." },
    ],
    wordsTitle: "Palabras bonitas",
    testimonialIds: ["oliwia", "india", "couple", "soul-brand"],
    faqTitle: "Preguntas frecuentes",
    faq: [
      { q: "Somos torpes delante de la cámara, ¿pasa algo?", a: "Para nada, a casi todo el mundo le pasa. No te hago \"posar\": te doy pequeñas indicaciones, caminamos, nos reímos y aparece tu verdadero yo." },
      { q: "¿Qué nos ponemos?", a: "Colores suaves y naturales y telas que se muevan con el viento. Tras reservar te envío una pequeña guía de estilo." },
      { q: "¿Cuál es la mejor hora?", a: "La hora dorada, justo después del amanecer o antes del atardecer. Yo elijo el horario según fecha y lugar." },
      { q: "¿Y si llueve?", a: "Cambiamos la sesión de día o abrazamos el drama de las nubes: tú decides." },
      { q: "¿Me ayudas con una pedida sorpresa?", a: "Sí. Te ayudo a elegir el sitio y el momento, y me escondo a plena vista." },
      { q: "¿Dónde fotografías?", a: "Cada sesión incluye el desplazamiento del Algarve a Lisboa, por la costa de por medio. Bodas, retiros, festivales y trabajos comerciales pueden ir más lejos, con el viaje a coste real." },
      { q: "¿Cómo reservo?", a: "Envía el formulario. Una señal del {deposit} asegura tu fecha." },
      { q: "¿Cuándo llega la galería?", a: "Las fotografías, en {artistWeeks}. El vídeo y las colecciones foto+vídeo, en {artistFilmWeeks}. La entrega exprés es un extra de pago: fotografías en {expressPhoto}, vídeo o el combo completo en {expressFilm}." },
    ],
    guide: { post: "ericeira", label: "Los lugares más mágicos para una sesión de pareja en Ericeira y Sintra" },
  },
  elopements: {
    eyebrow: "Bodas boho y elopements",
    title: "Para quienes van descalzos, arden y viven libres.",
    subtitle: "Elopements boho del Algarve a Lisboa, y más lejos",
    dek: "Votos descalzos. Unas pocas personas que amáis. Un día que se siente como libertad.",
    cta: "Consultar mi fecha",
    inquiry: "elopement",
    whoTitle: "Esto es para vosotros si…",
    who: [
      "Os fugáis a solas o invitáis solo a los más cercanos (hasta unas 30 personas)",
      "Preferís decir los votos en una playa, un bosque o junto al río antes que en un gran salón",
      "Vuestro día soñado incluye un handfasting, una ceremonia de cacao, coronas de flores, tambores, un círculo de fuego o una cena larga bajo las estrellas",
      "Queréis estar presentes, no que os dirijan",
    ],
    notFor:
      "No es para vosotros si planeáis una boda grande y tradicional: me dedico solo a celebraciones pequeñas e íntimas para poner todo mi corazón en cada una.",
    packagesTitle: "Colecciones",
    filmsTitle: "Vídeo",
    addonsTitle: "Extras",
    packages: {
      elopement: {
        name: "Elopement",
        items: [
          "3–4 horas: preparativos si los queréis, ceremonia y retratos",
          "Ayuda para elegir el lugar y la luz",
          "Unas 100 fotos editadas en una galería privada",
          "Adelanto en 48 horas, galería completa en {weeks}",
        ],
      },
      wedding: {
        name: "Boda íntima",
        badge: "la favorita",
        items: [
          "Hasta unas 30 personas",
          "5–6 horas, de la ceremonia a la noche: fuego, música, baile",
          "Más de 200 fotos editadas",
          "Adelanto en 48 horas, galería completa en {weeks}",
        ],
      },
      "elopement-film": {
        name: "Película de elopement",
        items: ["Una película de 3–5 minutos de la ceremonia y los retratos", "Entrega en {filmWeeks}"],
      },
      "wedding-film": {
        name: "Highlight de boda íntima",
        items: ["Una película de la ceremonia, los retratos y la noche", "Para compartirla con quien no pudo estar", "Entrega en {filmWeeks}"],
      },
      "elopement-photo-express": {
        name: "Fotos exprés",
        items: ["Un adelanto de 15–20 fotos editadas en 48 horas", "Galería completa en la mitad del tiempo habitual"],
      },
      "elopement-film-express": {
        name: "Vídeo exprés",
        items: [
          "Acelera la película de elopement o el highlight de boda íntima",
          "Lista en {expressFilm} en lugar de {filmWeeks}",
          "Un extra de pago: añádelo al reservar",
        ],
      },
      "elopement-drone-stills": {
        name: "Extra de fotos con dron",
        items: [
          "Un conjunto aéreo corto, añadido a vuestro elopement o boda íntima",
          "El lugar, los dos en el paisaje, el encuentro visto desde arriba",
          "Volamos solo cuando el tiempo y el espacio aéreo lo permiten",
        ],
      },
      "elopement-drone-story": {
        name: "Extra de foto + vídeo con dron",
        items: [
          "Fotos aéreas y una película corta, añadidas al día",
          "Un vuelo junto a la cobertura en tierra, no una producción aparte",
          "Volamos solo cuando el tiempo y el espacio aéreo lo permiten",
        ],
      },
    },
    travelNote:
      "El desplazamiento del Algarve a Lisboa está incluido. Los elopements y las bodas íntimas más lejos — el resto de Portugal, Europa y más allá — se presupuestan a coste real.",
    dayTitle: "Cómo podría ser vuestro día",
    day: "Votos al amanecer en una playa salvaje. Un paseo por el bosque con flores en el pelo. Una ceremonia guiada por un amigo, un chamán o un oficiante. Vuestra gente en círculo, tambores y risas. Una mesa larga bajo guirnaldas de luz. Una danza de fuego para cerrar la noche.",
    comingSoon: "Próximamente: nuestra primera historia completa de elopement boho. Hasta entonces, estas son fotos de pareja y de encuentros, no un día de boda.",
    processTitle: "Cómo funciona",
    process: [
      { title: "Contadme vuestra historia", body: "Rellenad el formulario con la fecha, el lugar (o \"ni idea todavía\") y cuántas personas seréis." },
      { title: "Hablemos", body: "Una videollamada relajada para sentir si encajamos." },
      { title: "Reserva", body: "Una señal del {deposit} asegura vuestra fecha. Entonces se puede añadir la entrega exprés." },
      { title: "Soñamos juntos", body: "Os ayudo con el lugar, el horario y el ritmo del día, y os recomiendo oficiantes, floristas y lugares afines." },
      { title: "El día y después", body: "Estoy con vosotros, como parte de ello. Adelanto en 48 horas. Las fotografías, en {weeks}; el vídeo, en {filmWeeks}." },
    ],
    wordsTitle: "Notas de amor",
    testimonialIds: ["elopement", "wedding"],
    faqTitle: "Preguntas frecuentes",
    faq: [
      { q: "¿Solo fotografías bodas pequeñas?", a: "Sí: elopements y celebraciones íntimas de hasta unas 30 personas. Ahí es donde mi estilo brilla de verdad." },
      { q: "¿Podemos hacer una ceremonia simbólica?", a: "Por supuesto. Muchas parejas se casan legalmente en su país y lo celebran aquí, en la naturaleza. Puedo recomendaros oficiantes." },
      { q: "Aún no sabemos dónde. ¿Nos ayudas?", a: "Es una de mis partes favoritas. Decidme vuestra vibra (océano, bosque, llanuras, montaña) y os propongo lugares." },
      { q: "¿También haces vídeo?", a: "Sí. La película de elopement y el highlight de boda íntima se reservan solos." },
      { q: "¿Fotografías fuego, noche y baile?", a: "La noche, el fuego y la luz de festival son mi especialidad. Vuestra fiesta está en buenas manos." },
      { q: "¿Viajas?", a: "Sí. La costa del Algarve a Lisboa está incluida. Para una boda también viajo por el resto de Portugal, Europa y más allá, incluidos destinos tropicales, con el desplazamiento a coste real." },
      { q: "¿Con cuánta antelación reservamos?", a: "Para mayo–octubre, lo ideal es con 6–12 meses; para un elopement a veces bastan unas semanas: pregúntame." },
      { q: "¿Cuándo llegan las fotografías y el vídeo?", a: "Las fotografías, en {weeks}. El vídeo sigue el plazo del vídeo, {filmWeeks}. El adelanto sale en 48 horas. La entrega exprés es un extra de pago: fotografías en {expressPhoto}, vídeo en {expressFilm}." },
    ],
    guide: { post: "boho", label: "Elopement boho en Portugal: lugares, temporadas y precios reales" },
  },
  retreats: {
    eyebrow: "Retiros y encuentros",
    title: "Para quienes van descalzos, arden y viven libres.",
    subtitle: "Fotógrafa de retiros, del Algarve a Lisboa y más lejos",
    dek: "Tu próximo retiro se vende con la sensación del anterior. Vamos a capturarla.",
    cta: "Planificar la cobertura de mi retiro",
    inquiry: "retreat",
    whoTitle: "Para quién",
    who: [
      "Organizadores de retiros de yoga, surf, breathwork, danza, cacao, sonido y bienestar",
      "Centros de retiro y eco-espacios que acogen grupos",
      "Facilitadores, terapeutas y guardianes de espacio con talleres y ceremonias",
      "Encuentros de comunidad, ecstatic dance y pequeños festivales conscientes",
    ],
    problemTitle: "Por qué importa",
    problem:
      "La gente reserva un retiro por lo que siente. Las imágenes honestas de una transformación real (el círculo, el silencio, las risas, la comida, el paisaje) son lo que hace que alguien pulse \"reservar\" en BookRetreats, Retreat Guru o tu web.",
    packagesTitle: "Paquetes",
    addonsTitle: "Extras",
    addonsNote:
      "Se añade a un día de retiro que ya estás reservando. Un vuelo tranquilo cuando el tiempo acompaña y el espacio aéreo lo permite: no es un día aéreo aparte.",
    packages: {
      "retreat-day": {
        name: "Retiro · 1 día",
        items: [
          "Un día completo (sesiones, rituales, comidas, momentos intermedios)",
          "Más de 150 fotos editadas con licencia comercial para tu web, anuncios y redes",
          "Selección y edición durante el retiro, con entrega nada más terminar",
        ],
      },
      "retreat-journey": {
        name: "Retiro · 3 días",
        badge: "la mejor para llenar futuras fechas",
        items: [
          "3 días documentando todo el arco: llegada, trabajo profundo, integración y despedidas",
          "Fotos y 5 reels verticales listos para Instagram, TikTok y tus anuncios",
          "Retratos de tus facilitadores para la página del equipo",
          "Licencia comercial incluida",
        ],
      },
      "retreat-custom": {
        name: "A medida",
        items: ["Retiros de una semana, festivales y ceremonias. Cuéntame el programa y te envío un presupuesto personalizado."],
      },
      "retreat-drone-addon": {
        name: "Extra de fotos con dron",
        items: [
          "Un conjunto aéreo tranquilo, añadido a la cobertura de retiro que ya estás reservando",
          "La tierra, el círculo desde arriba, el camino de llegada — para tu próximo anuncio",
          "Volamos cuando el tiempo acompaña y el espacio aéreo lo permite",
        ],
      },
    },
    travelNote:
      "Los retiros en la costa del Algarve a Lisboa incluyen mi desplazamiento. Los que quedan más lejos — el resto de Portugal, Europa y más allá — se presupuestan a coste real. El alojamiento y las comidas en el lugar suelen correr a cargo del retiro.",
    consentTitle: "Cómo trabajo en espacios sagrados",
    consent: [
      "Me presento en el círculo de apertura para que todos se sientan seguros.",
      "Acordamos qué momentos son sin cámara (ceremonias, picos de breathwork, círculos de integración).",
      "Cualquiera puede decir que no, con una pulsera o una señal sencilla.",
      "Tú apruebas la selección antes de publicar nada.",
    ],
    processTitle: "Cómo funciona",
    process: [
      { title: "Comparte tu programa", body: "Fechas, lugar, tamaño del grupo y qué quieres mostrar." },
      { title: "Lista de tomas", body: "Lo que tus futuros participantes necesitan ver: espacio, comida, práctica, personas, paisaje." },
      { title: "Me uno al retiro", body: "Presente, discreta, parte de él." },
      { title: "Entrega", body: "Galerías y reels listos para tu próximo lanzamiento." },
    ],
    wordsTitle: "Palabras bonitas",
    testimonialIds: ["retreat"],
    faqTitle: "Preguntas frecuentes",
    faq: [
      { q: "¿Una fotógrafa no altera la energía del grupo?", a: "No cuando forma parte de él. Me muevo con suavidad, respeto el silencio y me aparto cuando hace falta." },
      { q: "¿Puedo usar las imágenes en anuncios y en plataformas?", a: "Sí, la licencia comercial para tu propio marketing está incluida." },
      { q: "¿También grabas vídeo?", a: "Sí, los reels y las películas cortas forman parte del paquete Journey o se añaden como extra." },
      { q: "¿Tienen que firmar algo los participantes?", a: "Antes del retiro te comparto un sistema sencillo de consentimiento, y cualquiera puede decir que no." },
      { q: "¿Viajas al extranjero?", a: "Sí. Los retiros son uno de los proyectos por los que salgo de la costa del Algarve a Lisboa: el resto de Portugal, España, Europa y destinos tropicales, con el viaje a coste real." },
      { q: "¿Con cuánta antelación reservo?", a: "Lo ideal es con 2–3 meses, sobre todo entre mayo y octubre." },
    ],
    guide: { post: "retreat", label: "Cómo fotografiar tu retiro para llenar el próximo" },
  },
  festivals: {
    eyebrow: "Festivales, DJs y artistas",
    title: "Fotógrafa y videógrafa de festivales, DJs y fire shows",
    dek: "Para quienes crean la magia: en el escenario, detrás de los platos y dentro del fuego.",
    cta: "Quiero mi contenido",
    inquiry: "artist",
    whoTitle: "Para quién",
    who: [
      "DJs y músicos que necesitan fotos de prensa, clips de sus sets y un showreel para conseguir bolos",
      "Artistas de fuego, flow y performance: el retrato nocturno, el fuego y el humo son mi especialidad",
      "Festivales, escenarios, talleres y crews que quieren contenido oficial y con consentimiento",
      "Bandas y artistas que quieren un videoclip orgánico y cinematográfico",
    ],
    packagesTitle: "Paquetes",
    filmsTitle: "Vídeo",
    combosTitle: "Foto + vídeo",
    addonsTitle: "Extras",
    addonsNote:
      "La prioridad de un fin de semana completo empieza desde 200 €. La tarifa sigue los días y las horas de cobertura, la rapidez con la que necesitas los archivos y si quieres fotografías, vídeo o las dos cosas. Foto y vídeo juntos llevan más tiempo que solo las fotografías. El vídeo estándar sigue llegando en {artistFilmWeeks}. Son extras de prioridad, encima de la cobertura. Escríbeme cómo es el encuentro y tendrás la tarifa clara antes de la señal del {deposit}. El vuelo con dron es aparte: un salto el mismo día, mientras ya estoy reservada para ese día de festival. Depende del tiempo y solo donde el espacio aéreo lo permite legalmente. No es la cobertura completa del evento desde el aire.",
    addonsCta: "Consultar este extra",
    packages: {
      "press-kit": {
        name: "Kit de prensa DJ / artista",
        items: ["Sesión de prensa de 2 horas, de día o de noche con fuego", "20–30 fotos editadas para prensa, portadas y redes", "Galería en {artistWeeks}"],
      },
      "live-set": {
        name: "Contenido de set en directo",
        items: ["Fotos de la actuación y de la sala, por noche", "Clips del set en 48 horas", "Galería completa en {artistWeeks}"],
      },
      "festival-day": {
        name: "Día de festival o evento",
        items: ["Un día entero de fotografías oficiales", "Selección el mismo día para redes", "Entrega en 2–4 semanas, según el número de días del evento"],
      },
      "festival-half": {
        name: "Medio día de festival",
        items: ["Medio día de fotografías oficiales", "Selección para redes", "Galería completa en {artistWeeks}"],
      },
      aftermovie: {
        name: "Aftermovie de festival",
        items: ["Una película corta del día, por cada día del evento", "Para publicarla cuando el encuentro termina", "Entrega en 2–4 semanas, según la duración del festival"],
      },
      "music-video": {
        name: "Videoclip",
        items: ["Concepto, rodaje y edición de un videoclip orgánico, de actuación o en la naturaleza", "El presupuesto final depende de la idea", "Entrega en 3–5 semanas"],
      },
      "reels-pack": {
        name: "Pack de reels",
        items: ["Varios vídeos verticales cortos para Instagram y TikTok", "Montados a partir de una sesión o un evento", "Entrega en {artistFilmWeeks}"],
      },
      "single-reel": {
        name: "Un reel",
        items: ["Un vídeo vertical, listo para publicar", "Entrega en {artistFilmWeeks}"],
      },
      "festival-combo": {
        name: "Día de festival, foto + aftermovie",
        items: [
          "Un día entero de fotografías oficiales y un aftermovie corto de ese día",
          "Selección el mismo día para redes",
          "Entrega en 3–5 semanas, según la duración del evento",
        ],
      },
      "press-kit-combo": {
        name: "Kit de prensa + pack de reels",
        items: [
          "La sesión de prensa de 2 horas y 20–30 fotos editadas",
          "Varios reels verticales cortos de la misma sesión",
          "Entrega en 3–4 semanas",
        ],
      },
      "live-set-combo": {
        name: "Fotos de set en directo + pack de reels",
        items: [
          "Fotos de la actuación y de la sala, esa noche",
          "Un conjunto de reels montados a partir del set",
          "Clips del set en 48 horas",
          "Entrega en 3–4 semanas",
        ],
      },
      "festival-express-photos": {
        name: "Selección de fotos al día siguiente",
        items: [
          "Un día de fotografías, con la selección al día siguiente",
          "Un extra de prioridad, encima del paquete de cobertura",
          "Las horas y la edición marcan la tarifa, confirmada antes de la señal del {deposit}",
        ],
      },
      "festival-express-teaser": {
        name: "Adelanto el mismo día",
        items: [
          "Un puñado de fotos para redes, el mismo día, si la agenda lo permite",
          "Solo fotografías, encima de la cobertura de ese día",
          "Una nota breve con el orden del día y, después, la tarifa antes de la señal del {deposit}",
        ],
      },
      "festival-express-weekend": {
        name: "Prioridad de fin de semana",
        badge: "Desde 200 €",
        items: [
          "Unos tres días de entrega exprés o prioritaria para el paquete completo",
          "Se presupuesta según los días, las horas y si es foto, vídeo o las dos cosas",
          "Foto y vídeo juntos llevan más tiempo que las fotografías solas",
          "Una conversación corta y, después, la tarifa clara antes de la señal del {deposit}",
        ],
      },
      "festival-drone-addon": {
        name: "Vuelo corto con dron · el mismo día",
        items: [
          "Un vuelo el mismo día, mientras ya estoy contigo en un día de festival reservado",
          "No es la cobertura completa del evento desde el aire: una mirada breve al recinto, al escenario y a la tierra",
          "Depende del tiempo, y solo donde volar está permitido",
        ],
      },
    },
    travelNote:
      "Las sesiones de artista del Algarve a Lisboa incluyen el desplazamiento. Festivales y trabajos comerciales más lejos — el resto de Portugal, Europa y más allá — se presupuestan a coste real.",
    videosTitle: "Mira",
    videosNote: "Algunos vídeos se abren en Instagram. Pulsa reproducir y los demás empiezan aquí.",
    processTitle: "Cómo funciona",
    process: [
      { title: "Cuéntame la visión", body: "Artista, evento, fecha y para qué lo necesitas." },
      { title: "Planificamos", body: "Ambiente, lugares e iluminación. El fuego requiere un montaje seguro y una persona de apoyo." },
      { title: "Rodamos", body: "Me muevo con la música y el fuego." },
      { title: "Entrega", body: "Selección para redes y, después, la galería completa y los montajes. Clips del set en 48 horas. Fotografías en {artistWeeks}. Vídeos en {artistFilmWeeks}: foto y vídeo juntos llevan más tiempo que solo las fotografías. La entrega prioritaria es un extra a escala, con tarifa antes de la señal del {deposit}." },
    ],
    wordsTitle: "Palabras bonitas",
    testimonialIds: ["rewild", "kliq", "nixie", "sage", "artist"],
    faqTitle: "Preguntas frecuentes",
    faq: [
      { q: "¿Fotografías en clubs oscuros y de noche?", a: "Sí: poca luz, luces de escenario, humo y fuego son mi zona de confort." },
      { q: "¿Puedo usar las fotos en mi press kit y en plataformas de streaming?", a: "Sí, el uso promocional está incluido." },
      { q: "¿Trabajas con festivales?", a: "Sí, dentro de equipos de contenido oficiales o asociados, y siempre respetando las normas de foto y de consentimiento de cada festival." },
      { q: "¿Grabas un videoclip completo?", a: "Sí, del concepto a la edición final. Cuéntame tu idea y tu presupuesto." },
      { q: "¿Cuándo llegan los clips?", a: "Los clips del set, en 48 horas. Las fotografías, en {artistWeeks}. El vídeo, y la foto con vídeo, en {artistFilmWeeks}: juntos llevan más tiempo que solo las fotografías. Los paquetes de foto + vídeo están con el resto: un día de festival con aftermovie en 3–5 semanas, según la duración del evento, y un kit de prensa o un set en directo con reels en 3–4 semanas. La entrega exprés y prioritaria es un extra aparte, presupuestado al trabajo: selección de fotos al día siguiente desde 75–100 €, un adelanto el mismo día desde 100–150 € si la agenda lo permite, y un fin de semana completo desde 200 €. Cuéntame los días, las horas y la rapidez que necesitas. Confirmo la tarifa antes de la señal del {deposit}." },
    ],
  },
  places: {
    eyebrow: "Lugares",
    title: "Foto y vídeo para eco-alojamientos, surf houses y lugares boutique conscientes",
    dek: "Haz que tus huéspedes sientan tu lugar antes de llegar.",
    cta: "Hablemos de tu lugar",
    inquiry: "place",
    whoTitle: "Para quién",
    who: [
      "Eco-quintas, casas rurales y agroturismos",
      "Surf houses, surf camps y retiros de surf y yoga",
      "Centros de retiro, glamping y alojamientos off-grid",
      "Pequeños hoteles boutique con alma",
    ],
    problemTitle: "El problema que resuelvo",
    problem:
      "Tu lugar es precioso, pero tus fotos son antiguas, genéricas o hechas con el móvil, no tienes tiempo para redes y dependes de Booking y Airbnb. Yo creo imágenes y reels honestos y cálidos que muestran la experiencia: la luz de la mañana, el desayuno del huerto, la parafina y el pelo salado, el fuego de la noche.",
    packagesTitle: "Paquetes",
    filmsTitle: "Vídeo",
    combosTitle: "Foto + vídeo",
    addonsTitle: "Extras",
    addonsNote:
      "Se añaden a una jornada de contenido. Los paquetes aéreos de arriba también se pueden reservar solos. Volamos cuando el tiempo acompaña y el espacio aéreo lo permite.",
    packages: {
      "hotel-photo": {
        name: "Día de contenido · foto",
        items: [
          "1 jornada, solo fotografías",
          "Fotos horizontales para la web, Booking, Airbnb y Google",
          "Fotos de lifestyle del lugar, la comida y el entorno",
          "Licencia comercial para tu propio marketing",
        ],
      },
      "hotel-film": {
        name: "Película del alojamiento",
        items: ["Una película corta de la estancia", "Cortes verticales para Instagram y TikTok", "Licencia comercial para tu propio marketing"],
      },
      "hotel-combo": {
        name: "Día foto + vídeo",
        items: ["La jornada en fotografías y en vídeo", "Una visita, los dos conjuntos", "Menos que reservarlos por separado"],
      },
      "places-drone-stills": {
        name: "Fotos aéreas mini",
        items: [
          "Un vuelo corto sobre el lugar: los tejados, el jardín, el camino hacia el agua",
          "Un conjunto pequeño de fotos aéreas editadas para tu web y tus anuncios",
          "Volamos cuando el tiempo acompaña y el espacio aéreo lo permite",
          "Licencia comercial para tu propio marketing",
        ],
      },
      "places-drone-story": {
        name: "Historia aérea · foto + vídeo",
        items: [
          "El mismo vuelo corto, en fotos y en una película aérea breve",
          "Lo justo para mostrar la tierra, la luz y cómo se asienta el lugar",
          "Volamos cuando el tiempo acompaña y el espacio aéreo lo permite",
          "Licencia comercial para tu propio marketing",
        ],
      },
      "places-drone-addon-stills": {
        name: "Extra de fotos con dron",
        items: [
          "Un conjunto aéreo corto, añadido a una jornada de contenido",
          "Fotos editadas desde arriba: la casa, la tierra, el camino de llegada",
          "Solo cuando el tiempo y el espacio aéreo lo permiten",
        ],
      },
      "places-drone-addon-story": {
        name: "Extra de foto + vídeo con dron",
        items: [
          "Fotos aéreas y una película corta, añadidas a la jornada",
          "Un vuelo, los dos conjuntos, junto a la cobertura en tierra",
          "El tiempo y el espacio aéreo permitido van primero",
        ],
      },
    },
    deliverablesTitle: "Qué recibes",
    deliverables: ["Fotos horizontales para OTAs y tu web", "Imágenes lifestyle", "Reels verticales", "Licencia comercial para tu propio marketing"],
    travelNote:
      "Una jornada de contenido del Algarve a Lisboa incluye el desplazamiento. Los trabajos comerciales más lejos — el resto de Portugal, Europa y más allá — se presupuestan a coste real.",
    comingSoon: "Las colaboraciones dedicadas con alojamientos y habitaciones siguen en marcha.",
    processTitle: "Cómo funciona",
    process: [
      { title: "Llamada de 15 minutos", body: "Tu lugar, tus huéspedes, tus objetivos." },
      { title: "Lista de tomas y plan", body: "Qué mostrar, qué habitaciones, qué momentos, y la mejor luz y temporada." },
      { title: "Jornada de contenido", body: "Trabajo con discreción alrededor de tus huéspedes." },
      { title: "Entrega", body: "Fotos listas para la web, reels verticales y un plan de publicación." },
    ],
    wordsTitle: "Palabras bonitas",
    testimonialIds: ["place"],
    faqTitle: "Preguntas frecuentes",
    faq: [
      { q: "¿Molestarás a mis huéspedes?", a: "No: me organizo según tu ocupación y siempre pregunto antes de fotografiar a nadie." },
      { q: "¿Traes modelos?", a: "Puedo venir con amigos de mi comunidad o trabajar con huéspedes que quieran participar." },
      { q: "¿Las fotos sirven para Booking y Airbnb?", a: "Sí: entrego un set limpio y horizontal que sigue las pautas de las plataformas, y otro más cálido, de lifestyle, para redes." },
      { q: "¿Podemos cambiar estancia por contenido?", a: "En temporada baja, y para nuevas colaboraciones, a veces ofrezco colaboraciones híbridas: pregúntame." },
    ],
  },
  portfolio: {
    title: "Portfolio",
    dek: "Momentos reales de las almas indómitas.",
    filters: [
      { id: "all", label: "Todo" },
      { id: "portraits", label: "Retratos y parejas" },
      { id: "elopements", label: "Elopements", soon: true },
      { id: "retreats", label: "Retiros y encuentros" },
      { id: "festivals", label: "Festivales" },
      { id: "djs", label: "DJs y música" },
      { id: "fire", label: "Fuego" },
      { id: "places", label: "Lugares" },
      { id: "film", label: "Vídeo" },
    ],
    empty: "Todavía no hay nada en este filtro.",
  },
  journal: {
    title: "Journal",
    dek: "Guías, historias e inspiración para parejas de espíritu libre, líderes de retiros y lugares conscientes.",
    read: "Leer la guía",
    related: "Una guía que puede ayudar",
    cta: "Cuéntame vuestros planes",
  },
  inquire: {
    title: "Creemos algo real.",
    dek: "Cuéntame un poco sobre ti y lo que sueñas. Leo cada mensaje personalmente y respondo en 48 horas.",
    prefer: "¿Prefieres hablar?",
    email: "Email",
    nextTitle: "¿Qué pasa después?",
    next: [
      "Te respondo en 48 horas con mi disponibilidad y algunas preguntas.",
      "Hacemos una llamada corta (vídeo o WhatsApp) para sentir si encajamos.",
      "Recibes una propuesta a medida. Una señal del {deposit} asegura tu fecha. La entrega exprés es un extra de pago si necesitas la galería antes.",
    ],
    confirm:
      "Gracias, alma bonita: tu mensaje ha llegado. Te escribo en 48 horas. Mientras tanto, pásate a saludar en Instagram @oracle.of.freedom.",
  },
  thankYou: {
    title: "Mensaje recibido",
    body: "Gracias, alma bonita: tu mensaje ha llegado. Te escribo en 48 horas. Mientras tanto, pásate a saludar en Instagram @oracle.of.freedom.",
    preview: "Vista previa: la consulta se ha validado, pero el email aún no está configurado. Añade RESEND_API_KEY antes de publicar.",
    again: "Volver al inicio",
  },
  privacy: {
    title: "Aviso de privacidad",
    updated: "Actualizado el 7 de octubre de 2026. Es un aviso breve, no una política legal completa.",
    sections: [
      { title: "Quién", body: ["Oracle of Freedom es Agota Urbikaite, con base del Algarve a Lisboa. Email: agota@oracleoffreedom.com."] },
      {
        title: "Qué recoge el formulario",
        body: [
          "Tu nombre, email, la historia que quieras contar y, si los das, teléfono, fecha, lugar, presupuesto y cómo me encontraste. Lo envías para que Agota pueda responder sobre una posible colaboración.",
          "Los mensajes se envían a agota@oracleoffreedom.com a través de Resend cuando ese servicio está configurado. Hasta entonces el formulario funciona, pero no se entrega nada.",
          "Las consultas se conservan solo el tiempo necesario para responder y seguir la conversación, y después se borran.",
        ],
      },
      {
        title: "Tus decisiones",
        body: [
          "Puedes pedir ver, corregir o borrar lo que enviaste escribiendo a agota@oracleoffreedom.com.",
          "Si no estás conforme con una respuesta sobre tus datos, puedes acudir a la autoridad portuguesa, la CNPD.",
        ],
      },
      {
        title: "Cookies y vídeos",
        body: [
          "Una cookie de idioma recuerda EN, ES o PT. Es necesaria para que el sitio se quede en el idioma que elegiste.",
          "Instagram y YouTube se cargan cuando pulsas reproducir en un vídeo. Si eliges solo lo esencial, se quedan como imagen y enlace hasta que pulsas reproducir.",
          "El sitio puede usar Vercel Web Analytics, que no usa cookies de marketing.",
          "El alojamiento es Vercel. El envío de email, cuando se active, es Resend. Se aplican sus propias condiciones.",
        ],
      },
    ],
  },
  form: {
    steps: ["El sueño", "Los detalles", "Cómo escribirte"],
    next: "Seguir",
    back: "Atrás",
    submit: "Enviar mi historia",
    sending: "Enviando…",
    name: "Tu nombre (o vuestros nombres)",
    email: "Email",
    phone: "WhatsApp / teléfono",
    service: "¿Qué estás soñando?",
    services: {
      portraits: "Sesión de retrato",
      proposal: "Pedida",
      "soul-brand": "Retrato personal / marca con alma",
      elopement: "Elopement",
      wedding: "Boda íntima boho (hasta unas 30)",
      retreat: "Retiro / encuentro",
      artist: "DJ / artista / fire show",
      "music-video": "Videoclip",
      festival: "Festival / evento",
      place: "Alojamiento (eco-quinta / surf house / boutique)",
      other: "Otra cosa",
    },
    date: "Fecha (o aproximada)",
    dateFrom: "Cobertura desde",
    dateTo: "Cobertura hasta",
    flexible: "Mi fecha es flexible",
    place: "¿Dónde? (del Algarve a Lisboa está incluido — o dime si es más lejos)",
    people: "¿Cuántas personas?",
    peopleOptions: { "1": "1", "2": "2", "3-10": "3–10", "11-30": "11–30", "30+": "Más de 30" },
    eventOptions: { "lt-10": "Menos de 10", "10-20": "10–20", "20-40": "20–40", "40+": "Más de 40" },
    days: "¿Cuántos días?",
    dayOptions: { "1": "1", "2-3": "2–3", "4-7": "4–7", "7+": "Más de 7" },
    placeType: "Tipo de alojamiento",
    placeTypes: {
      quinta: "Eco-quinta",
      surf: "Surf house / camp",
      retreat: "Centro de retiro",
      boutique: "Hotel boutique",
      glamping: "Glamping",
      other: "Otro",
    },
    website: "Web / Instagram",
    budget: "Tu presupuesto para foto/vídeo",
    budgetUnsure: "No lo sé",
    budgets,
    media: "Foto, vídeo o ambos",
    mediaOptions: { photo: "Foto", film: "Vídeo", both: "Ambos" },
    story: "Cuéntame sobre ti y tu visión",
    storyPlaceholder: "La vibra, el lugar, lo que más importa…",
    found: "¿Cómo me encontraste?",
    foundOptions: {
      instagram: "Instagram",
      google: "Google",
      pinterest: "Pinterest",
      tiktok: "TikTok",
      friend: "Un amigo / un cliente anterior",
      retreat: "Retiro / lugar / oficiante",
      directory: "Directorio (EscapeElopements, Photo Portugal…)",
      festival: "Festival / evento",
      other: "Otro",
    },
    language: "Idioma preferido",
    languages: { en: "English", es: "Español", lt: "Lietuvių" },
    consent: "Acepto que me contacten sobre mi consulta.",
    promoCode: "Código promocional",
    promoHint: "Opcional. Si tienes uno, va con tu mensaje.",
    wish: "¿Qué te gustaría?",
    wishPlaceholder: "Quién viene, cuánto tiempo, qué lugar y qué quieres que se sientan las fotografías.",
    errors: {
      required: "Este campo hace falta.",
      email: "Añade un email al que Agota pueda responder.",
      consent: "Hace falta el consentimiento para enviar el mensaje.",
      date: "Añade una fecha o marca que tu fecha es flexible.",
      dateEnd: "Añade la fecha final o marca que tu fecha es flexible.",
      dateOrder: "La fecha final tiene que ser el mismo día o posterior.",
    },
    weddingLimit:
      "Solo fotografío celebraciones íntimas de hasta unas 30 personas, para poner todo el corazón en el día. Una boda más grande queda fuera de este trabajo; una sesión de retrato a menudo sí encaja. Puedes enviar la nota: responderé con sinceridad.",
    fail: "El mensaje no se ha enviado. Escribe a agota@oracleoffreedom.com y llegará igual.",
  },
};
