import type { Copy } from "./types";

const budgets = {
  portraits: [
    { value: "lt-175", label: "Menos de 175 €" },
    { value: "175-300", label: "175–300 €" },
    { value: "300-500", label: "300–500 €" },
    { value: "500+", label: "500 € ou mais" },
  ],
  weddings: [
    { value: "lt-650", label: "Menos de 650 €" },
    { value: "650-1100", label: "650–1.100 €" },
    { value: "1100-1650", label: "1.100–1.650 €" },
    { value: "1650+", label: "1.650 € ou mais" },
  ],
  retreats: [
    { value: "lt-400", label: "Menos de 400 €" },
    { value: "400-1000", label: "400–1.000 €" },
    { value: "1000-2000", label: "1.000–2.000 €" },
    { value: "2000+", label: "2.000 € ou mais" },
  ],
  artists: [
    { value: "lt-110", label: "Menos de 110 €" },
    { value: "110-300", label: "110–300 €" },
    { value: "300-600", label: "300–600 €" },
    { value: "600+", label: "600 € ou mais" },
  ],
  places: [
    { value: "lt-475", label: "Menos de 475 €" },
    { value: "475-900", label: "475–900 €" },
    { value: "900+", label: "900 € ou mais" },
  ],
  other: [
    { value: "lt-175", label: "Menos de 175 €" },
    { value: "175-600", label: "175–600 €" },
    { value: "600-1500", label: "600–1.500 €" },
    { value: "1500+", label: "1.500 € ou mais" },
  ],
};

export const pt: Copy = {
  meta: {
    home: {
      title: "Oracle of Freedom · Fotografia e vídeo, Algarve e Lisboa",
      description:
        "Fotografia e vídeo para espíritos livres, do Algarve a Lisboa. Casamentos, retiros, festivais e trabalhos comerciais viajam mais longe: o resto de Portugal, a Europa e mais além.",
      keywords: "fotógrafa Algarve e Lisboa; fotógrafa Algarve; fotógrafa Lisboa; fotógrafa boho Portugal",
    },
    about: {
      title: "Sobre a Agota · Fotógrafa do Algarve a Lisboa",
      description:
        "Conhece a Agota Urbikaite. Cada sessão cobre do Algarve a Lisboa. Casamentos, retiros, festivais e trabalhos comerciais podem ir mais longe.",
      keywords: "Agota Urbikaite fotógrafa; fotógrafa Algarve e Lisboa; fotografia espontânea Portugal",
    },
    people: {
      title: "Pessoas · Retratos e casamentos íntimos boho",
      description:
        "Retratos e casamentos íntimos boho do Algarve a Lisboa, costa incluída. Os casamentos podem viajar mais longe. Sessões desde 175 €.",
      keywords: "fotógrafa de casal Algarve; fotógrafa de casamentos Lisboa; casamento boho Portugal",
    },
    portraits: {
      title: "Sessão de casal e de noivado · Algarve e Lisboa",
      description:
        "Sessões de retrato para uma pessoa, um casal, uma família ou amigos, do Algarve a Lisboa. Naturais, sem poses. Desde 175 €.",
      keywords: "fotógrafa de casal Algarve; noivado Lisboa; sessão fotográfica Algarve; pedido de casamento Lisboa",
    },
    elopements: {
      title: "Fotógrafa de elopements boho · Algarve e Lisboa",
      description:
        "Elopements íntimos do Algarve a Lisboa, e mais longe por Portugal, Europa e mais além. Círculos pequenos, até cerca de 30 pessoas. Desde 690 €.",
      keywords: "fotógrafa elopement Algarve; elopement Lisboa; casamento boho Portugal; casamento íntimo",
    },
    experiences: {
      title: "Experiências · Retiros, festivais e artistas",
      description:
        "Retiros, festivais, DJs e artistas de fogo. Com base do Algarve a Lisboa, e a viajar mais longe para os encontros grandes.",
      keywords: "fotógrafa de retiros Algarve; fotógrafa de festivais Lisboa; fotógrafa de retiros Portugal",
    },
    retreats: {
      title: "Fotógrafa de retiros · Algarve, Lisboa e mais além",
      description:
        "Fotografia e vídeo de retiros do Algarve a Lisboa, e mais longe por Portugal e pela Europa. Com consentimento e licença comercial. Desde 400 €/dia.",
      keywords: "fotógrafa retiros Algarve; fotógrafa retiros Lisboa; fotógrafa retiros de yoga; vídeo para retiros",
    },
    festivals: {
      title: "Fotógrafa de festivais e DJs · Algarve e Lisboa",
      description:
        "Fotos de imprensa, clips de sets, retratos de fogo e videoclipes. Do Algarve a Lisboa, e em viagem para festivais e trabalhos comerciais. Desde 190 €.",
      keywords: "fotógrafa de festivais Algarve; fotógrafo DJ Lisboa; espetáculo de fogo; videoclipe Portugal",
    },
    places: {
      title: "Fotógrafa de eco-alojamentos · Algarve e Lisboa",
      description:
        "Fotografias e reels para eco-quintas, surf houses e alojamentos boutique do Algarve a Lisboa. Os trabalhos comerciais podem viajar mais longe. Desde 475 €.",
      keywords: "fotógrafa turismo rural Algarve; surf house Lisboa; fotógrafa Airbnb Algarve; alojamento local",
    },
    portfolio: {
      title: "Portefólio · Oracle of Freedom",
      description: "Momentos reais das almas indomáveis. Retratos, encontros, festivais, fogo, DJs e vídeo.",
      keywords: "portefólio Agota Urbikaite; fotógrafa boho Portugal",
    },
    journal: {
      title: "Journal · Guias para espíritos livres",
      description:
        "Guias para um elopement boho em Portugal, fotografar um retiro para encher o seguinte, e sessões de casal na Ericeira e em Sintra.",
      keywords: "elopement boho Algarve; sessão de casal Lisboa; fotografia de retiros",
    },
    inquire: {
      title: "Contacto · Oracle of Freedom",
      description: "Conta-me a tua história: data, local e sonho. Respondo em 48 horas. Também por WhatsApp ou email.",
      keywords: "contactar fotógrafa Algarve; contactar fotógrafa Lisboa",
    },
    book: {
      title: "Marca uma chamada · Oracle of Freedom",
      description: "Escolhe uma hora para conhecer a fotógrafa e videógrafa Agota Urbikaite.",
      keywords: "marcar Agota Urbikaite; marcar fotógrafa Algarve; marcar fotógrafa Lisboa",
    },
    privacy: {
      title: "Privacidade · Oracle of Freedom",
      description: "Como a Oracle of Freedom usa os dados do formulário, as cookies e os vídeos incorporados. Um aviso breve de RGPD.",
      keywords: "privacidade Oracle of Freedom; RGPD",
    },
  },
  a11y: {
    skip: "Saltar para o conteúdo",
    menu: "Abrir menu",
    closeMenu: "Fechar menu",
    home: "Oracle of Freedom, início",
    openPhoto: "Abrir fotografia",
    close: "Fechar",
    previous: "Anterior",
    next: "Seguinte",
    photoPlaceholder: "Marcador em baixa resolução — será substituído",
    language: "Língua",
  },
  nav: {
    people: "Pessoas",
    experiences: "Experiências",
    places: "Lugares",
    portfolio: "Portefólio",
    about: "Sobre mim",
    journal: "Journal",
    book: "Marcar",
    inquire: "Contacto",
  },
  footer: {
    blurb:
      "Fotografia e vídeo por Agota Urbikaite, do Algarve a Lisboa. Casamentos, retiros, festivais e trabalhos comerciais viajam mais longe.",
    privacy: "Privacidade",
    rights: "Todos os direitos reservados.",
  },
  whatsapp: {
    button: "Fala comigo",
    general: "Olá Agota! Encontrei-te em oracleoffreedom.com e gostava muito de falar contigo 🌿",
    portraits: "Olá Agota! Gostava de uma sessão de retrato por volta de [data] em [local]. Digo-te quem vem e o que gostava:",
    elopements: "Olá Agota! Sonhamos com um elopement boho íntimo por volta de [data] 💛",
    retreats: "Olá Agota! Organizo um retiro em [datas] e gostava da tua cobertura",
    festivals: "Olá Agota! Sou DJ/artista e preciso de conteúdo para…",
    places: "Olá Agota! Tenho o [espaço] e gostava de falar sobre conteúdo",
  },
  common: {
    explore: "Descobrir",
    viewPortfolio: "Ver portefólio",
    readGuides: "Ler os guias",
    meet: "Conhecer a Agota",
    from: "Desde",
    priceNote: "Preços desde, em EUR e sem IVA. Casamentos, alojamentos e festivais confirmam-se com um orçamento.",
    offer: "Oferta",
    saveSeparately: "Poupam {amount} em relação a reservar em separado",
    placeholderTitle: "Pendente — não é um testemunho publicado",
    placeholderBody: "As citações reais substituem isto quando a Agota tiver autorização para as partilhar. Aqui não há textos inventados.",
    comingSoon: "Em breve",
    mostLoved: "a preferida",
    closingTitle: "A tua história, sentida por dentro.",
    closingBody:
      "Conta-me o que sonhas: um pôr do sol nas falésias, uma semana de breathwork entre colinas, uma noite de fogo e tambores. Digo-te com honestidade como posso ajudar.",
    closingPrimary: "Ver disponibilidade",
    closingSecondary: "ou fala comigo no WhatsApp",
    checkAvailability: "Ver disponibilidade",
    seeWork: "Ver o trabalho",
  },
  cookies: {
    text: "Este site guarda uma preferência de língua e, só se aceitares, carrega vídeos do Instagram e do YouTube. Sem cookies de marketing.",
    accept: "Aceitar vídeos",
    essential: "Só o essencial",
    privacy: "Aviso de privacidade",
  },
  home: {
    title: "Para espíritos livres, encontros sagrados e lugares com alma.",
    dek: "Fotografia e vídeo para espíritos livres: casais apaixonados, encontros sagrados, almas de festival e os lugares que os acolhem. Cada sessão do Algarve a Lisboa; casamentos, retiros, festivais e trabalhos comerciais, mais longe.",
    manifesto:
      "Não olho de fora. Danço à beira do fogo, entro no mar contigo, sento-me no círculo. É aí que vivem os momentos verdadeiros, e é aí que está a minha câmara.",
    doorsTitle: "Três portas",
    peopleTitle: "Pessoas",
    peopleBody: "Retratos, sessões de noivado e casamentos íntimos boho e elopements. Luz dourada, cabelo salgado, amor verdadeiro.",
    peoplePrice: "Sessões desde {session} · Elopements desde {elopement}",
    experiencesTitle: "Experiências",
    experiencesBody: "Retiros, encontros, festivais, DJs, artistas de fogo e flow, videoclipes. A energia do momento, captada por dentro.",
    experiencesPrice: "Cobertura de retiros desde {retreat}/dia",
    placesTitle: "Lugares",
    placesBody: "Eco-quintas, surf houses e alojamentos boutique conscientes. Imagens e reels que fazem sentir o teu espaço antes da chegada.",
    placesPrice: "Dias de conteúdo desde {places}",
    howTitle: "Como trabalho",
    how: [
      { title: "Torno-me parte do momento.", body: "Sem poses rígidas nem presença invasiva. Movo-me com o fluxo para que te esqueças da câmara." },
      { title: "Fotografia e vídeo, uma só pessoa.", body: "Um olhar e um coração: menos equipa, mais intimidade." },
      { title: "Consentimento, sempre.", body: "Em círculos, cerimónias e festivais, ninguém é fotografado ou partilhado sem o seu sim." },
    ],
    featuredTitle: "Trabalho em destaque",
    wordsTitle: "Palavras bonitas",
    about:
      "Olá, sou a Agota. Há mais de 10 anos que fotografo e filmo os momentos em que ninguém posa, captando a essência e a magia dos eventos, das comunidades e das almas indomáveis.",
    journalTitle: "Journal",
    journalDek: "Guias para quem sonha e para quem organiza.",
    closingTitle: "Conta-me a tua história.",
    follow: "Segue @oracle.of.freedom",
    igNote: "Uma grelha quieta do portefólio. A que está viva é no Instagram.",
  },
  about: {
    title: "Olá, sou a Agota.",
    paragraphs: [
      "Trabalho com fotografia e vídeo há mais de 10 anos, tanto a nível profissional como em projetos de paixão. Especializo-me em captar momentos espontâneos a sério e em dar vida à magia de um evento ou de uma comunidade, em imagens fixas e em edições de vídeo.",
      "O meu estilo é fluido e orgânico: um equilíbrio delicado entre energias opostas, a ação e a calma. Não se trata apenas de captar o momento, mas de estar nele; não apenas de estar à volta da ação, mas de fazer parte dela. É isso que dá profundidade ao meu trabalho, e é aí que se captam os momentos mais doces e genuínos, aqueles em que quem vê passa a fazer parte de tudo.",
      "Sinto-me atraída por pessoas e lugares de espírito livre: encontros na selva, cerimónias junto ao rio, votos descalços na praia, DJs perdidos no seu set, casas ecológicas construídas com amor. E é essa a magia que quero captar.",
    ],
    promise: "Oracle of Freedom é a minha promessa: ver-te como realmente és e libertar esse momento.",
    valuesTitle: "Aquilo em que acredito",
    values: [
      { title: "Presença", body: "Entrego-me por inteiro, para que também tu o possas fazer." },
      { title: "Consentimento", body: "Os teus momentos são teus. Pergunto, escuto e respeito os espaços sem câmara." },
      { title: "Liberdade", body: "Sem guiões nem poses forçadas; apenas uma orientação suave quando quiseres." },
      { title: "Comunidade", body: "Faço parte dos círculos que fotografo e trato-os com cuidado." },
    ],
    facts: "Mais de 10 anos em fotografia e vídeo · Fotografia e vídeo · Línguas: inglês e lituano com fluência, e espanhol de conversação",
    bts: "PENDENTE — fotografias da Agota a trabalhar, ainda por fazer. Este bloco fica vazio até existirem.",
    closingTitle: "Vamos criar algo verdadeiro juntos.",
  },
  people: {
    title: "Pessoas",
    dek: "Retratos, histórias de amor e casamentos íntimos boho, fotografados com calor, liberdade e zero rigidez.",
    portraitsTitle: "Sessões de retrato",
    portraitsBody: "Uma sessão para pessoas, casais, noivado, famílias e amigos. O preço de partida ajusta-se ao que queres.",
    portraitsPrice: "Desde {price}",
    weddingsTitle: "Casamentos boho e elopements",
    weddingsBody: "Votos descalços, um pequeno círculo de pessoas queridas, cerimónias à vossa imagem.",
    weddingsPrice: "Desde {price}",
    wordsTitle: "Palavras bonitas",
  },
  experiences: {
    title: "Experiências",
    dek: "Retiros, encontros, festivais, DJs, artistas de fogo e flow, e videoclipes, fotografados e filmados de dentro do círculo.",
    retreatsTitle: "Retiros e encontros",
    retreatsBody: "Fotografias e reels que ajudam a encher o teu próximo retiro.",
    retreatsPrice: "Desde {price}/dia",
    festivalsTitle: "Festivais, DJs e artistas",
    festivalsBody: "Fotografias de imprensa, clips de sets, espetáculos de fogo, showreels e videoclipes.",
    festivalsPrice: "Desde {price}",
    consentTitle: "Consentimento, sempre.",
    consent:
      "Os espaços sagrados merecem respeito. Combinamos os momentos sem câmara, posso usar pulseiras ou sinais para quem não quiser aparecer, e nada é publicado sem aprovação.",
  },
  portraits: {
    eyebrow: "Sessões de retrato",
    title: "Para os descalços, os incendiados e os livres.",
    subtitle: "Sessões de retrato, do Algarve a Lisboa",
    dek: "Uma sessão para ti, para dois ou para as pessoas que amas. Pessoas, casais, noivado, famílias e amigos.",
    cta: "Marcar sessão",
    personalizeCta: "Personaliza a tua sessão",
    personalizeWhatsapp: "ou escreve no WhatsApp",
    inquiry: "portraits",
    whoTitle: "Para quem",
    who: [
      "Uma pessoa, um casal, um noivado, uma família ou um grupo de amigos",
      "Pedidos surpresa, aniversários e férias juntos",
      "Quem quiser fotografias naturais, sem poses rígidas",
      "Professores de yoga, terapeutas, facilitadores, músicos e artistas que precisam de imagens com alma para a sua marca",
    ],
    packagesTitle: "Sessões",
    filmsTitle: "Vídeo",
    combosTitle: "Foto + vídeo",
    addonsTitle: "Entrega expressa",
    packages: {
      "portrait-sessions": {
        name: "Sessões de retrato",
        items: [
          "Pessoas, casais, noivado, famílias, amigos: qualquer grupo",
          "Começa numa hora. A duração, as fotografias editadas, os locais e quantas pessoas dão forma ao preço final",
          "Orientação suave, sem poses rígidas",
          "Uma galeria privada em {artistWeeks}, pronta a descarregar e partilhar",
        ],
      },
      "couples-film": {
        name: "Filme de casal",
        items: ["Um filme curto da sessão, cerca de 60–90 segundos", "Um corte vertical para stories", "Entrega em {artistFilmWeeks}"],
      },
      "couples-combo": {
        name: "Sessão de retrato + vídeo",
        items: ["A sessão de retrato e o filme curto", "Uma só pessoa, uma tarde", "Fotografias e filme em {artistFilmWeeks}: foto+vídeo segue o prazo do filme"],
      },
      "portrait-film-express": {
        name: "Filme expresso",
        items: [
          "Acelera o filme de casal",
          "Pronto em {expressFilm} em vez de {artistFilmWeeks}",
          "Um extra pago: acrescenta-o na marcação",
        ],
      },
      "portrait-combo-express": {
        name: "Foto + vídeo expresso",
        items: [
          "Acelera a sessão de retrato e o filme juntos",
          "Os dois em {expressFilm} em vez de {artistFilmWeeks}",
          "As fotografias sozinhas podem ir expressas em {expressPhoto}",
        ],
      },
    },
    travelNote:
      "A deslocação está incluída em cada sessão, do Algarve a Lisboa, com a costa pelo meio. Casamentos, retiros, festivais e trabalhos comerciais podem ir mais longe — o resto de Portugal, a Europa e mais além — com a viagem ao custo real.",
    whereTitle: "Onde podemos fotografar",
    where:
      "Todo o Algarve e a costa até Lisboa: o sul, a Costa Vicentina, o litoral alentejano, Comporta, a Arrábida e a cidade. A Ericeira e Sintra ficam mesmo a norte de Lisboa — diz-me se é esse o plano. Para um casamento, um retiro, um festival ou um trabalho comercial, o resto de Portugal, a Europa e mais além estão abertos.",
    processTitle: "Como funciona",
    process: [
      { title: "Diz olá", body: "Envia o formulário ou uma mensagem de WhatsApp com a data que imaginas e aquilo que sonhas." },
      { title: "Planeamos", body: "Sugiro locais, o horário para a melhor luz e o que vestir." },
      { title: "A sessão", body: "Descontraída, divertida, verdadeira. Oriento-te quando precisas e desapareço quando não." },
      { title: "Revive tudo", body: "Chega a tua galeria privada em {artistWeeks}, pronta a descarregar, partilhar e imprimir. Os filmes e as coleções foto+vídeo seguem o prazo do filme, {artistFilmWeeks}." },
    ],
    wordsTitle: "Palavras bonitas",
    testimonialIds: ["oliwia", "india", "couple", "soul-brand"],
    faqTitle: "Perguntas frequentes",
    faq: [
      { q: "Somos desajeitados à frente da câmara. Faz mal?", a: "Nada. Acontece a quase toda a gente. Não vos ponho a \"posar\": dou pequenas sugestões, caminhamos, rimo-nos e o vosso verdadeiro eu aparece." },
      { q: "O que devemos vestir?", a: "Cores suaves e naturais e tecidos que se mexam com o vento. Depois da marcação envio um pequeno guia de estilo." },
      { q: "Qual é a melhor hora?", a: "A hora dourada, logo a seguir ao nascer do sol ou antes do pôr do sol. Eu escolho o horário conforme a data e o local." },
      { q: "E se chover?", a: "Mudamos a sessão para outro dia ou abraçamos o drama das nuvens: vocês decidem." },
      { q: "Ajudas num pedido de casamento surpresa?", a: "Sim. Ajudo-te a escolher o sítio e o momento, e escondo-me à vista de todos." },
      { q: "Onde fotografas?", a: "Cada sessão inclui a deslocação do Algarve a Lisboa, pela costa pelo meio. Casamentos, retiros, festivais e trabalhos comerciais podem ir mais longe, com a viagem ao custo real." },
      { q: "Como marco?", a: "Envia o formulário. Um sinal de {deposit} garante a tua data." },
      { q: "Quando chega a galeria?", a: "As fotografias, em {artistWeeks}. Os filmes e as coleções foto+vídeo, em {artistFilmWeeks}. A entrega expressa é um extra pago: fotografias em {expressPhoto}, filme ou o combo completo em {expressFilm}." },
    ],
    guide: { post: "ericeira", label: "Os sítios mais mágicos para uma sessão de casal na Ericeira e em Sintra" },
  },
  elopements: {
    eyebrow: "Casamentos boho e elopements",
    title: "Para os descalços, os incendiados e os livres.",
    subtitle: "Elopements boho do Algarve a Lisboa, e mais longe",
    dek: "Votos descalços. Meia dúzia de pessoas que amam. Um dia que sabe a liberdade.",
    cta: "Ver a minha data",
    inquiry: "elopement",
    whoTitle: "Isto é para vocês se…",
    who: [
      "Vão fugir a dois ou convidar só os mais próximos (até cerca de 30 pessoas)",
      "Preferem dizer os votos numa praia, numa floresta ou junto ao rio em vez de num grande salão",
      "O vosso dia de sonho inclui um handfasting, uma cerimónia de cacau, coroas de flores, tambores, um círculo de fogo ou um longo jantar sob as estrelas",
      "Querem estar presentes, não ser dirigidos",
    ],
    notFor:
      "Não é para vocês se estão a planear um casamento grande e tradicional: dedico-me apenas a celebrações pequenas e íntimas, para dar todo o meu coração a cada uma.",
    packagesTitle: "Coleções",
    filmsTitle: "Vídeo",
    addonsTitle: "Extras",
    packages: {
      elopement: {
        name: "Elopement",
        items: [
          "3–4 horas: preparativos se os quiserem, cerimónia e retratos",
          "Ajuda na escolha do local e da luz",
          "Cerca de 100 fotografias editadas numa galeria privada",
          "Antevisão em 48 horas, galeria completa em {weeks}",
        ],
      },
      wedding: {
        name: "Casamento íntimo",
        badge: "a preferida",
        items: [
          "Até cerca de 30 pessoas",
          "5–6 horas, da cerimónia à noite: fogo, música, dança",
          "Mais de 200 fotografias editadas",
          "Antevisão em 48 horas, galeria completa em {weeks}",
        ],
      },
      "elopement-film": {
        name: "Filme de elopement",
        items: ["Um filme de 3–5 minutos da cerimónia e dos retratos", "Entrega em {filmWeeks}"],
      },
      "wedding-film": {
        name: "Highlight de casamento íntimo",
        items: ["Um filme da cerimónia, dos retratos e da noite", "Para partilhar com quem não pôde estar", "Entrega em {filmWeeks}"],
      },
      "elopement-photo-express": {
        name: "Fotos expresso",
        items: ["Uma pré-visualização de 15–20 fotos editadas em 48 horas", "Galeria completa em metade do tempo habitual"],
      },
      "elopement-film-express": {
        name: "Filme expresso",
        items: [
          "Acelera o filme de elopement ou o highlight de casamento íntimo",
          "Pronto em {expressFilm} em vez de {filmWeeks}",
          "Um extra pago: acrescenta-o na marcação",
        ],
      },
      "elopement-drone-stills": {
        name: "Extra de fotos com drone",
        items: [
          "Um conjunto aéreo curto, acrescentado ao vosso elopement ou casamento íntimo",
          "O lugar, os dois na paisagem, o encontro visto de cima",
          "Voamos só quando o tempo e o espaço aéreo o permitem",
        ],
      },
      "elopement-drone-story": {
        name: "Extra de foto + filme com drone",
        items: [
          "Fotografias aéreas e um filme curto, acrescentados ao dia",
          "Um voo ao lado da cobertura em terra, não uma produção à parte",
          "Voamos só quando o tempo e o espaço aéreo o permitem",
        ],
      },
    },
    travelNote:
      "A deslocação do Algarve a Lisboa está incluída. Elopements e casamentos íntimos mais longe — o resto de Portugal, a Europa e mais além — orçamentam-se ao custo real.",
    dayTitle: "Como pode ser o vosso dia",
    day: "Votos ao nascer do sol numa praia selvagem. Um passeio pela floresta com flores no cabelo. Uma cerimónia conduzida por um amigo, um xamã ou um celebrante. A vossa gente em círculo, tambores e gargalhadas. Uma mesa comprida sob luzinhas. Uma dança de fogo para fechar a noite.",
    comingSoon: "Em breve: a nossa primeira história completa de elopement boho. Até lá, estas são fotografias de casal e de encontros, não um dia de casamento.",
    processTitle: "Como funciona",
    process: [
      { title: "Contem-me a vossa história", body: "Preencham o formulário com a data, o local (ou \"ainda não sabemos\") e quantas pessoas vão ser." },
      { title: "Vamos conversar", body: "Uma videochamada descontraída para sentirmos se há sintonia." },
      { title: "Reserva", body: "Um sinal de {deposit} garante a vossa data. A entrega expressa pode acrescentar-se nessa altura." },
      { title: "Sonhamos juntos", body: "Ajudo com o local, o horário e o ritmo do dia, e recomendo celebrantes, floristas e espaços afins." },
      { title: "O dia e depois", body: "Estou convosco, como parte do momento. Antevisão em 48 horas. As fotografias, em {weeks}; os filmes, em {filmWeeks}." },
    ],
    wordsTitle: "Notas de amor",
    testimonialIds: ["elopement", "wedding"],
    faqTitle: "Perguntas frequentes",
    faq: [
      { q: "Só fotografas casamentos pequenos?", a: "Sim: elopements e celebrações íntimas até cerca de 30 pessoas. É aí que o meu estilo brilha de verdade." },
      { q: "Podemos fazer uma cerimónia simbólica?", a: "Claro. Muitos casais casam legalmente no seu país e celebram aqui, na natureza. Posso recomendar celebrantes." },
      { q: "Ainda não sabemos onde. Ajudas?", a: "É uma das minhas partes preferidas. Digam-me a vossa vibe (oceano, floresta, planície, montanha) e eu sugiro lugares." },
      { q: "Também fazes vídeo?", a: "Sim. O filme de elopement e o highlight de casamento íntimo reservam-se sozinhos." },
      { q: "Fotografas fogo, noite e dança?", a: "A noite, o fogo e a luz de festival são a minha especialidade. A vossa festa está em boas mãos." },
      { q: "Viajas?", a: "Sim. A costa do Algarve a Lisboa está incluída. Para um casamento também viajo pelo resto de Portugal, pela Europa e mais além, incluindo destinos tropicais, com a deslocação ao custo real." },
      { q: "Com quanta antecedência devemos reservar?", a: "Para maio–outubro, o ideal são 6–12 meses; para um elopement às vezes bastam algumas semanas: perguntem." },
      { q: "Quando chegam as fotografias e o filme?", a: "As fotografias, em {weeks}. Os filmes seguem o prazo do filme, {filmWeeks}. A antevisão sai em 48 horas. A entrega expressa é um extra pago: fotografias em {expressPhoto}, filme em {expressFilm}." },
    ],
    guide: { post: "boho", label: "Elopement boho em Portugal: locais, épocas e preços reais" },
  },
  retreats: {
    eyebrow: "Retiros e encontros",
    title: "Para os descalços, os incendiados e os livres.",
    subtitle: "Fotógrafa de retiros, do Algarve a Lisboa e mais longe",
    dek: "O teu próximo retiro vende-se com a sensação do anterior. Vamos captá-la.",
    cta: "Planear a cobertura do meu retiro",
    inquiry: "retreat",
    whoTitle: "Para quem",
    who: [
      "Organizadores de retiros de yoga, surf, breathwork, dança, cacau, som e bem-estar",
      "Centros de retiro e eco-espaços que recebem grupos",
      "Facilitadores, terapeutas e guardiões de espaço com workshops e cerimónias",
      "Encontros de comunidade, ecstatic dance e pequenos festivais conscientes",
    ],
    problemTitle: "Porque é importante",
    problem:
      "As pessoas reservam um retiro pelo que sentem. Imagens honestas de uma transformação real (o círculo, o silêncio, as gargalhadas, a comida, a paisagem) são o que faz alguém carregar em \"reservar\" no BookRetreats, no Retreat Guru ou no teu site.",
    packagesTitle: "Pacotes",
    addonsTitle: "Extras",
    addonsNote:
      "Acrescenta-se a um dia de retiro que já estás a reservar. Um voo calmo quando o tempo ajuda e o espaço aéreo permite — não é um dia aéreo à parte.",
    packages: {
      "retreat-day": {
        name: "Retiro · 1 dia",
        items: [
          "Um dia completo (sessões, rituais, refeições, momentos intermédios)",
          "Mais de 150 fotografias editadas com licença comercial para o teu site, anúncios e redes",
          "Seleção e edição durante o retiro, com entrega assim que termina",
        ],
      },
      "retreat-journey": {
        name: "Retiro · 3 dias",
        badge: "o melhor para encher datas futuras",
        items: [
          "3 dias a documentar todo o percurso: chegada, trabalho profundo, integração e despedidas",
          "Fotografias e 5 reels verticais prontos para Instagram, TikTok e anúncios",
          "Retratos dos teus facilitadores para a página da equipa",
          "Licença comercial incluída",
        ],
      },
      "retreat-custom": {
        name: "À medida",
        items: ["Retiros de uma semana, festivais e cerimónias. Partilha o programa e envio um orçamento personalizado."],
      },
      "retreat-drone-addon": {
        name: "Extra de fotos com drone",
        items: [
          "Um conjunto aéreo calmo, acrescentado à cobertura de retiro que já estás a reservar",
          "A terra, o círculo visto de cima, o caminho de chegada — para o teu próximo anúncio",
          "Voamos quando o tempo ajuda e o espaço aéreo permite",
        ],
      },
    },
    travelNote:
      "Os retiros na costa do Algarve a Lisboa incluem a minha deslocação. Os que ficam mais longe — o resto de Portugal, a Europa e mais além — orçamentam-se ao custo real. O alojamento e as refeições no local costumam ficar a cargo do retiro.",
    consentTitle: "Como trabalho em espaços sagrados",
    consent: [
      "Apresento-me no círculo de abertura, para que todos se sintam seguros.",
      "Combinamos que momentos são sem câmara (cerimónias, picos de breathwork, partilhas de integração).",
      "Qualquer pessoa pode dizer que não, com uma pulseira ou um sinal simples.",
      "Tu aprovas a seleção antes de qualquer publicação.",
    ],
    processTitle: "Como funciona",
    process: [
      { title: "Partilha o teu programa", body: "Datas, local, tamanho do grupo e o que queres mostrar." },
      { title: "Lista de planos", body: "O que os teus futuros participantes precisam de ver: espaço, comida, prática, pessoas, paisagem." },
      { title: "Junto-me ao retiro", body: "Presente, discreta, parte dele." },
      { title: "Entrega", body: "Galerias e reels prontos para o teu próximo lançamento." },
    ],
    wordsTitle: "Palavras bonitas",
    testimonialIds: ["retreat"],
    faqTitle: "Perguntas frequentes",
    faq: [
      { q: "Uma fotógrafa não perturba a energia do grupo?", a: "Não quando faz parte dele. Movo-me com suavidade, respeito o silêncio e afasto-me quando é preciso." },
      { q: "Posso usar as imagens em anúncios e plataformas?", a: "Sim, a licença comercial para o teu próprio marketing está incluída." },
      { q: "Também filmas?", a: "Sim, os reels e os filmes curtos fazem parte do pacote Journey ou podem ser acrescentados como extra." },
      { q: "Os participantes têm de assinar alguma coisa?", a: "Antes do retiro partilho contigo um sistema simples de consentimento, e qualquer pessoa pode dizer que não." },
      { q: "Viajas para o estrangeiro?", a: "Sim. Os retiros são um dos projetos pelos quais saio da costa do Algarve a Lisboa: o resto de Portugal, Espanha, a Europa e destinos tropicais, com a viagem ao custo real." },
      { q: "Com quanta antecedência devo marcar?", a: "O ideal são 2–3 meses, sobretudo entre maio e outubro." },
    ],
    guide: { post: "retreat", label: "Como fotografar o teu retiro para encher o próximo" },
  },
  festivals: {
    eyebrow: "Festivais, DJs e artistas",
    title: "Fotógrafa e videógrafa de festivais, DJs e espetáculos de fogo",
    dek: "Para quem cria a magia: no palco, atrás dos pratos e dentro do fogo.",
    cta: "Quero o meu conteúdo",
    inquiry: "artist",
    whoTitle: "Para quem",
    who: [
      "DJs e músicos que precisam de fotografias de imprensa, clips dos sets e um showreel para conseguir datas",
      "Artistas de fogo, flow e performance: o retrato noturno, o fogo e o fumo são a minha especialidade",
      "Festivais, palcos, workshops e crews que querem conteúdo oficial e com consentimento",
      "Bandas e artistas que querem um videoclipe orgânico e cinematográfico",
    ],
    packagesTitle: "Pacotes",
    filmsTitle: "Vídeo",
    combosTitle: "Foto + vídeo",
    addonsTitle: "Extras",
    addonsNote:
      "A prioridade de um fim de semana completo começa desde 200 €. O valor segue os dias e as horas de cobertura, a rapidez com que precisas dos ficheiros e se queres fotografias, filme ou os dois. Foto e filme juntos demoram mais do que só as fotografias. O filme padrão continua a chegar em {artistFilmWeeks}. São extras de prioridade, por cima da cobertura. Escreve-me como é o encontro e ficas com o valor claro antes do sinal de {deposit}. O voo de drone é à parte: um salto no próprio dia, enquanto já estou marcada para esse dia de festival. Depende do tempo e só onde o espaço aéreo o permite legalmente. Não é a cobertura completa do evento a partir do ar.",
    addonsCta: "Perguntar sobre este extra",
    packages: {
      "press-kit": {
        name: "Kit de imprensa DJ / artista",
        items: ["Sessão de imprensa de 2 horas, de dia ou de noite com fogo", "20–30 fotografias editadas para imprensa, capas e redes", "Galeria em {artistWeeks}"],
      },
      "live-set": {
        name: "Conteúdo de set ao vivo",
        items: ["Fotografias da atuação e da sala, por noite", "Clips do set em 48 horas", "Galeria completa em {artistWeeks}"],
      },
      "festival-day": {
        name: "Dia de festival ou evento",
        items: ["Um dia inteiro de fotografias oficiais", "Seleção no próprio dia para as redes", "Entrega em 2–4 semanas, conforme o número de dias do evento"],
      },
      "festival-half": {
        name: "Meio dia de festival",
        items: ["Meio dia de fotografias oficiais", "Seleção para as redes", "Galeria completa em {artistWeeks}"],
      },
      aftermovie: {
        name: "Aftermovie de festival",
        items: ["Um filme curto do dia, por cada dia do evento", "Para publicar quando o encontro termina", "Entrega em 2–4 semanas, conforme a duração do festival"],
      },
      "music-video": {
        name: "Videoclipe",
        items: ["Conceito, filmagem e edição de um videoclipe orgânico, de atuação ou na natureza", "O orçamento final depende da ideia", "Entrega em 3–5 semanas"],
      },
      "reels-pack": {
        name: "Pack de reels",
        items: ["Vários vídeos verticais curtos para Instagram e TikTok", "Montados a partir de uma sessão ou de um evento", "Entrega em {artistFilmWeeks}"],
      },
      "single-reel": {
        name: "Um reel",
        items: ["Um vídeo vertical, pronto a publicar", "Entrega em {artistFilmWeeks}"],
      },
      "festival-combo": {
        name: "Dia de festival, foto + aftermovie",
        items: [
          "Um dia inteiro de fotografias oficiais e um aftermovie curto desse dia",
          "Seleção no próprio dia para as redes",
          "Entrega em 3–5 semanas, conforme a duração do evento",
        ],
      },
      "press-kit-combo": {
        name: "Kit de imprensa + pack de reels",
        items: [
          "A sessão de imprensa de 2 horas e 20–30 fotografias editadas",
          "Um conjunto de reels verticais curtos da mesma sessão",
          "Entrega em 3–4 semanas",
        ],
      },
      "live-set-combo": {
        name: "Fotos de set ao vivo + pack de reels",
        items: [
          "Fotografias da atuação e da sala, nessa noite",
          "Um conjunto de reels montados a partir do set",
          "Clips do set em 48 horas",
          "Entrega em 3–4 semanas",
        ],
      },
      "festival-express-photos": {
        name: "Seleção de fotos no dia seguinte",
        items: [
          "Um dia de fotografias, com a seleção no dia seguinte",
          "Um extra de prioridade, por cima do pacote de cobertura",
          "As horas e a edição definem o valor, confirmado antes do sinal de {deposit}",
        ],
      },
      "festival-express-teaser": {
        name: "Antevisão no próprio dia",
        items: [
          "Um punhado de fotos para as redes, no próprio dia, quando a agenda permite",
          "Só fotografias, por cima da cobertura desse dia",
          "Uma nota breve com a ordem do dia e, depois, o valor antes do sinal de {deposit}",
        ],
      },
      "festival-express-weekend": {
        name: "Prioridade de fim de semana",
        badge: "Desde 200 €",
        items: [
          "Cerca de três dias de entrega expressa ou prioritária para o pacote completo",
          "Orçamenta-se pelos dias, pelas horas e se é foto, filme ou os dois",
          "Foto e filme juntos demoram mais do que as fotografias sozinhas",
          "Uma conversa curta e, depois, o valor claro antes do sinal de {deposit}",
        ],
      },
      "festival-drone-addon": {
        name: "Voo curto de drone · no próprio dia",
        items: [
          "Um voo no próprio dia, enquanto já estou contigo num dia de festival marcado",
          "Não é a cobertura completa do evento a partir do ar: um olhar breve ao recinto, ao palco e à terra",
          "Depende do tempo, e só onde voar é permitido",
        ],
      },
    },
    travelNote:
      "As sessões de artista do Algarve a Lisboa incluem a deslocação. Festivais e trabalhos comerciais mais longe — o resto de Portugal, a Europa e mais além — orçamentam-se ao custo real.",
    videosTitle: "Vê",
    videosNote: "Alguns vídeos abrem no Instagram. Carrega em reproduzir e os outros começam aqui.",
    processTitle: "Como funciona",
    process: [
      { title: "Conta-me a visão", body: "Artista, evento, data e para que precisas." },
      { title: "Planeamos", body: "Ambiente, locais e iluminação. O fogo exige uma montagem segura e uma pessoa de apoio." },
      { title: "Filmamos", body: "Movo-me com a música e com o fogo." },
      { title: "Entrega", body: "Seleção para as redes e, depois, a galeria completa e as montagens. Clips do set em 48 horas. Fotografias em {artistWeeks}. Filmes em {artistFilmWeeks}: foto e filme juntos demoram mais do que só as fotografias. A entrega prioritária é um extra em escala, com o valor antes do sinal de {deposit}." },
    ],
    wordsTitle: "Palavras bonitas",
    testimonialIds: ["rewild", "kliq", "nixie", "sage", "artist"],
    faqTitle: "Perguntas frequentes",
    faq: [
      { q: "Fotografas em clubes escuros e à noite?", a: "Sim: pouca luz, luzes de palco, fumo e fogo são a minha zona de conforto." },
      { q: "Posso usar as fotografias no press kit e nas plataformas de streaming?", a: "Sim, a utilização promocional está incluída." },
      { q: "Trabalhas com festivais?", a: "Sim, integrada em equipas de conteúdo oficiais ou parceiras, e sempre dentro das regras de fotografia e consentimento de cada festival." },
      { q: "Filmas um videoclipe completo?", a: "Sim, do conceito à edição final. Conta-me a tua ideia e o teu orçamento." },
      { q: "Quando chegam os clips?", a: "Os clips do set, em 48 horas. As fotografias, em {artistWeeks}. O filme, e a foto com filme, em {artistFilmWeeks}: juntos demoram mais do que só as fotografias. Os pacotes de foto + vídeo estão com os restantes: um dia de festival com aftermovie em 3–5 semanas, conforme a duração do evento, e um kit de imprensa ou um set ao vivo com reels em 3–4 semanas. A entrega expressa e prioritária é um extra à parte, orçamentado ao trabalho: seleção de fotos no dia seguinte desde 75–100 €, uma antevisão no próprio dia desde 100–150 € quando a agenda permite, e um fim de semana completo desde 200 €. Conta-me os dias, as horas e a rapidez de que precisas. Confirmo o valor antes do sinal de {deposit}." },
    ],
  },
  places: {
    eyebrow: "Lugares",
    title: "Fotografia e vídeo para eco-alojamentos, surf houses e espaços boutique conscientes",
    dek: "Faz com que os teus hóspedes sintam o teu espaço antes de chegarem.",
    cta: "Vamos falar do teu espaço",
    inquiry: "place",
    whoTitle: "Para quem",
    who: [
      "Eco-quintas, turismo rural e agroturismo",
      "Surf houses, surf camps e retiros de surf e yoga",
      "Centros de retiro, glamping e alojamentos off-grid",
      "Pequenos hotéis boutique com alma",
    ],
    problemTitle: "O problema que resolvo",
    problem:
      "O teu espaço é lindo, mas as fotografias são antigas, genéricas ou tiradas com o telemóvel, não tens tempo para as redes sociais e dependes do Booking e do Airbnb. Crio imagens e reels honestos e calorosos que mostram a experiência: a luz da manhã, o pequeno-almoço da horta, a parafina e o cabelo salgado, a fogueira à noite.",
    packagesTitle: "Pacotes",
    filmsTitle: "Vídeo",
    combosTitle: "Foto + vídeo",
    addonsTitle: "Extras",
    addonsNote:
      "Acrescentam-se a um dia de conteúdo. Os pacotes aéreos acima também se podem reservar sozinhos. Voamos quando o tempo ajuda e o espaço aéreo permite.",
    packages: {
      "hotel-photo": {
        name: "Dia de conteúdo · foto",
        items: [
          "1 dia, só fotografias",
          "Fotografias horizontais para o site, Booking, Airbnb e Google",
          "Fotografias de lifestyle do espaço, da comida e da envolvente",
          "Licença comercial para o teu próprio marketing",
        ],
      },
      "hotel-film": {
        name: "Filme do alojamento",
        items: ["Um filme curto da estadia", "Cortes verticais para Instagram e TikTok", "Licença comercial para o teu próprio marketing"],
      },
      "hotel-combo": {
        name: "Dia foto + vídeo",
        items: ["O dia em fotografias e em vídeo", "Uma visita, os dois conjuntos", "Menos do que reservar os dois em separado"],
      },
      "places-drone-stills": {
        name: "Fotos aéreas mini",
        items: [
          "Um voo curto sobre o espaço: os telhados, o jardim, o caminho até à água",
          "Um conjunto pequeno de fotografias aéreas editadas para o teu site e anúncios",
          "Voamos quando o tempo ajuda e o espaço aéreo permite",
          "Licença comercial para o teu próprio marketing",
        ],
      },
      "places-drone-story": {
        name: "História aérea · foto + filme",
        items: [
          "O mesmo voo curto, em fotografias e num filme aéreo breve",
          "O suficiente para mostrar a terra, a luz e o sítio onde o espaço assenta",
          "Voamos quando o tempo ajuda e o espaço aéreo permite",
          "Licença comercial para o teu próprio marketing",
        ],
      },
      "places-drone-addon-stills": {
        name: "Extra de fotos com drone",
        items: [
          "Um conjunto aéreo curto, acrescentado a um dia de conteúdo",
          "Fotografias editadas de cima: a casa, a terra, o caminho de chegada",
          "Só quando o tempo e o espaço aéreo o permitem",
        ],
      },
      "places-drone-addon-story": {
        name: "Extra de foto + filme com drone",
        items: [
          "Fotografias aéreas e um filme curto, acrescentados ao dia",
          "Um voo, os dois conjuntos, ao lado da cobertura em terra",
          "O tempo e o espaço aéreo permitido vêm primeiro",
        ],
      },
    },
    deliverablesTitle: "O que recebes",
    deliverables: ["Fotografias horizontais para OTAs e o teu site", "Imagens lifestyle", "Reels verticais", "Licença comercial para o teu próprio marketing"],
    travelNote:
      "Um dia de conteúdo do Algarve a Lisboa inclui a deslocação. Trabalhos comerciais mais longe — o resto de Portugal, a Europa e mais além — orçamentam-se ao custo real.",
    comingSoon: "As colaborações dedicadas com alojamentos e quartos continuam a caminho.",
    processTitle: "Como funciona",
    process: [
      { title: "Chamada de 15 minutos", body: "O teu espaço, os teus hóspedes, os teus objetivos." },
      { title: "Lista de planos", body: "O que mostrar, que quartos, que momentos, e a melhor luz e época." },
      { title: "Dia de conteúdo", body: "Trabalho com discrição à volta dos teus hóspedes." },
      { title: "Entrega", body: "Fotografias prontas para o site, reels verticais e um plano de publicação." },
    ],
    wordsTitle: "Palavras bonitas",
    testimonialIds: ["place"],
    faqTitle: "Perguntas frequentes",
    faq: [
      { q: "Vais incomodar os meus hóspedes?", a: "Não: organizo-me de acordo com a tua ocupação e peço sempre autorização antes de fotografar alguém." },
      { q: "Trazes modelos?", a: "Posso trazer amigos da minha comunidade ou trabalhar com hóspedes que queiram participar." },
      { q: "As fotografias servem para o Booking e o Airbnb?", a: "Sim: entrego um conjunto limpo e horizontal que segue as regras das plataformas, e outro mais caloroso, de lifestyle, para as redes." },
      { q: "Podemos trocar estadia por conteúdo?", a: "Na época baixa, e para novas parcerias, às vezes proponho colaborações híbridas: pergunta-me." },
    ],
  },
  portfolio: {
    title: "Portefólio",
    dek: "Momentos reais das almas indomáveis.",
    filters: [
      { id: "all", label: "Tudo" },
      { id: "portraits", label: "Retratos e casais" },
      { id: "elopements", label: "Elopements", soon: true },
      { id: "retreats", label: "Retiros e encontros" },
      { id: "festivals", label: "Festivais" },
      { id: "djs", label: "DJs e música" },
      { id: "fire", label: "Fogo" },
      { id: "places", label: "Lugares" },
      { id: "film", label: "Vídeo" },
    ],
    empty: "Ainda não há nada neste filtro.",
  },
  journal: {
    title: "Journal",
    dek: "Guias, histórias e inspiração para casais de espírito livre, líderes de retiros e espaços conscientes.",
    read: "Ler o guia",
    related: "Um guia que pode ajudar",
    cta: "Conta-me os vossos planos",
  },
  inquire: {
    title: "Vamos criar algo verdadeiro.",
    dek: "Conta-me um pouco sobre ti e sobre o que sonhas. Leio cada mensagem pessoalmente e respondo em 48 horas.",
    prefer: "Preferes conversar?",
    email: "Email",
    nextTitle: "O que acontece a seguir?",
    next: [
      "Respondo em 48 horas com a minha disponibilidade e algumas perguntas.",
      "Fazemos uma chamada curta (vídeo ou WhatsApp) para sentir se há sintonia.",
      "Recebes uma proposta à medida. Um sinal de {deposit} garante a tua data. A entrega expressa é um extra pago se precisares da galeria mais cedo.",
    ],
    confirm:
      "Obrigada, alma bonita: a tua mensagem chegou. Respondo-te em 48 horas. Entretanto, passa pelo Instagram @oracle.of.freedom para dizer olá.",
  },
  thankYou: {
    title: "Mensagem recebida",
    body: "Obrigada, alma bonita: a tua mensagem chegou. Respondo-te em 48 horas. Entretanto, passa pelo Instagram @oracle.of.freedom para dizer olá.",
    preview: "Pré-visualização: o pedido foi validado, mas o email ainda não está configurado. Adiciona RESEND_API_KEY antes de publicar.",
    again: "Voltar ao início",
  },
  privacy: {
    title: "Aviso de privacidade",
    updated: "Atualizado a 7 de outubro de 2026. É um aviso breve, não uma política jurídica completa.",
    sections: [
      { title: "Quem", body: ["Oracle of Freedom é a Agota Urbikaite, com base do Algarve a Lisboa. Email: agota@oracleoffreedom.com."] },
      {
        title: "O que o formulário recolhe",
        body: [
          "O teu nome, email, a história que quiseres contar e, se os deres, telefone, data, local, orçamento e como me encontraste. Envias isto para a Agota poder responder sobre uma possível colaboração.",
          "As mensagens seguem para agota@oracleoffreedom.com através da Resend quando esse serviço está configurado. Até lá o formulário funciona, mas nada é entregue.",
          "Os pedidos conservam-se só o tempo necessário para responder e acompanhar a conversa, e depois apagam-se.",
        ],
      },
      {
        title: "As tuas escolhas",
        body: [
          "Podes pedir para ver, corrigir ou apagar o que enviaste, escrevendo para agota@oracleoffreedom.com.",
          "Se não ficares satisfeito com uma resposta sobre os teus dados, podes contactar a autoridade portuguesa, a CNPD.",
        ],
      },
      {
        title: "Cookies e vídeos",
        body: [
          "Uma cookie de língua lembra EN, ES ou PT. É necessária para o site ficar na língua que escolheste.",
          "O Instagram e o YouTube carregam quando carregas em reproduzir num vídeo. Se escolheres só o essencial, ficam como imagem e ligação até carregares em reproduzir.",
          "O site pode usar o Vercel Web Analytics, que não usa cookies de marketing.",
          "O alojamento é na Vercel. O envio de email, quando estiver ativo, é a Resend. Aplicam-se os termos deles.",
        ],
      },
    ],
  },
  form: {
    steps: ["O sonho", "Os detalhes", "Como falar contigo"],
    next: "Continuar",
    back: "Voltar",
    submit: "Enviar a minha história",
    sending: "A enviar…",
    name: "O teu nome (ou os vossos)",
    email: "Email",
    phone: "WhatsApp / telemóvel",
    service: "Com o que sonhas?",
    services: {
      portraits: "Sessão de retrato",
      proposal: "Pedido de casamento",
      "soul-brand": "Retrato pessoal / marca com alma",
      elopement: "Elopement",
      wedding: "Casamento íntimo boho (até cerca de 30)",
      retreat: "Retiro / encontro",
      artist: "DJ / artista / espetáculo de fogo",
      "music-video": "Videoclipe",
      festival: "Festival / evento",
      place: "Espaço (eco-quinta / surf house / boutique)",
      other: "Outra coisa",
    },
    date: "Data (ou aproximada)",
    dateFrom: "Cobertura de",
    dateTo: "Cobertura até",
    flexible: "A minha data é flexível",
    place: "Onde? (do Algarve a Lisboa está incluído — ou diz-me se é mais longe)",
    people: "Quantas pessoas?",
    peopleOptions: { "1": "1", "2": "2", "3-10": "3–10", "11-30": "11–30", "30+": "Mais de 30" },
    eventOptions: { "lt-10": "Menos de 10", "10-20": "10–20", "20-40": "20–40", "40+": "Mais de 40" },
    days: "Quantos dias?",
    dayOptions: { "1": "1", "2-3": "2–3", "4-7": "4–7", "7+": "Mais de 7" },
    placeType: "Tipo de espaço",
    placeTypes: {
      quinta: "Eco-quinta",
      surf: "Surf house / camp",
      retreat: "Centro de retiro",
      boutique: "Hotel boutique",
      glamping: "Glamping",
      other: "Outro",
    },
    website: "Site / Instagram",
    budget: "O teu orçamento para foto/vídeo",
    budgetUnsure: "Não sei",
    budgets,
    media: "Foto, vídeo ou ambos",
    mediaOptions: { photo: "Foto", film: "Vídeo", both: "Ambos" },
    story: "Conta-me sobre ti e a tua visão",
    storyPlaceholder: "A vibe, o sítio, o que mais importa…",
    found: "Como me encontraste?",
    foundOptions: {
      instagram: "Instagram",
      google: "Google",
      pinterest: "Pinterest",
      tiktok: "TikTok",
      friend: "Um amigo / um cliente anterior",
      retreat: "Retiro / espaço / celebrante",
      directory: "Diretório (EscapeElopements, Photo Portugal…)",
      festival: "Festival / evento",
      other: "Outro",
    },
    language: "Língua preferida",
    languages: { en: "English", es: "Español", lt: "Lietuvių" },
    consent: "Aceito ser contactado/a sobre o meu pedido.",
    promoCode: "Código promocional",
    promoHint: "Opcional. Se tiveres um, segue com a tua mensagem.",
    wish: "O que gostavas?",
    wishPlaceholder: "Quem vem, quanto tempo, que sítio e o que queres que as fotografias transmitam.",
    errors: {
      required: "Este campo é preciso.",
      email: "Acrescenta um email para o qual a Agota possa responder.",
      consent: "É preciso o consentimento para enviar a mensagem.",
      date: "Acrescenta uma data ou marca que a tua data é flexível.",
      dateEnd: "Acrescenta a data final ou marca que a tua data é flexível.",
      dateOrder: "A data final tem de ser no mesmo dia ou depois.",
    },
    weddingLimit:
      "Só fotografo celebrações íntimas até cerca de 30 pessoas, para dar todo o coração ao dia. Um casamento maior fica fora deste trabalho; uma sessão de retrato muitas vezes ainda encaixa. Podes enviar a nota: respondo com honestidade.",
    fail: "A mensagem não foi enviada. Escreve para agota@oracleoffreedom.com e chega na mesma.",
  },
};
