export type Step = { title: string; body: string };
export type FaqItem = { q: string; a: string };
export type PackageCopy = { name: string; items: string[]; badge?: string };
export type BudgetOption = { value: string; label: string };

export type ServiceCopy = {
  eyebrow: string;
  title: string;
  subtitle?: string;
  dek: string;
  cta: string;
  personalizeCta?: string;
  personalizeWhatsapp?: string;
  inquiry: string;
  whoTitle: string;
  who: string[];
  notFor?: string;
  problemTitle?: string;
  problem?: string;
  packagesTitle: string;
  filmsTitle?: string;
  combosTitle?: string;
  packages: Record<string, PackageCopy>;
  addonsTitle?: string;
  addonsNote?: string;
  addonsCta?: string;
  travelNote?: string;
  whereTitle?: string;
  where?: string;
  dayTitle?: string;
  day?: string;
  deliverablesTitle?: string;
  deliverables?: string[];
  consentTitle?: string;
  consentIntro?: string;
  consent?: string[];
  processTitle: string;
  process: Step[];
  wordsTitle: string;
  testimonialIds: string[];
  faqTitle: string;
  faq: FaqItem[];
  guide?: { post: "boho" | "retreat" | "ericeira"; label: string };
  comingSoon?: string;
  videosTitle?: string;
  videosNote?: string;
};

export type Copy = {
  meta: Record<string, { title: string; description: string; keywords: string }>;
  a11y: {
    skip: string;
    menu: string;
    closeMenu: string;
    home: string;
    openPhoto: string;
    close: string;
    previous: string;
    next: string;
    photoPlaceholder: string;
    language: string;
  };
  nav: {
    people: string;
    experiences: string;
    places: string;
    portfolio: string;
    about: string;
    journal: string;
    inquire: string;
  };
  footer: { blurb: string; privacy: string; rights: string };
  whatsapp: {
    button: string;
    general: string;
    portraits: string;
    elopements: string;
    retreats: string;
    festivals: string;
    places: string;
  };
  common: {
    explore: string;
    viewPortfolio: string;
    readGuides: string;
    meet: string;
    from: string;
    priceNote: string;
    offer: string;
    saveSeparately: string;
    placeholderTitle: string;
    placeholderBody: string;
    comingSoon: string;
    mostLoved: string;
    closingTitle: string;
    closingBody: string;
    closingPrimary: string;
    closingSecondary: string;
    checkAvailability: string;
    seeWork: string;
  };
  cookies: { text: string; accept: string; essential: string; privacy: string };
  home: {
    title: string;
    dek: string;
    manifesto: string;
    doorsTitle: string;
    peopleTitle: string;
    peopleBody: string;
    peoplePrice: string;
    experiencesTitle: string;
    experiencesBody: string;
    experiencesPrice: string;
    placesTitle: string;
    placesBody: string;
    placesPrice: string;
    howTitle: string;
    how: { title: string; body: string }[];
    featuredTitle: string;
    wordsTitle: string;
    about: string;
    journalTitle: string;
    journalDek: string;
    closingTitle: string;
    follow: string;
    igNote: string;
  };
  about: {
    title: string;
    paragraphs: string[];
    promise: string;
    valuesTitle: string;
    values: { title: string; body: string }[];
    facts: string;
    bts: string;
    closingTitle: string;
  };
  people: {
    title: string;
    dek: string;
    portraitsTitle: string;
    portraitsBody: string;
    portraitsPrice: string;
    weddingsTitle: string;
    weddingsBody: string;
    weddingsPrice: string;
  };
  experiences: {
    title: string;
    dek: string;
    retreatsTitle: string;
    retreatsBody: string;
    retreatsPrice: string;
    festivalsTitle: string;
    festivalsBody: string;
    festivalsPrice: string;
    consentTitle: string;
    consent: string;
  };
  portraits: ServiceCopy;
  elopements: ServiceCopy;
  retreats: ServiceCopy;
  festivals: ServiceCopy;
  places: ServiceCopy;
  portfolio: {
    title: string;
    dek: string;
    filters: { id: string; label: string; soon?: boolean }[];
    empty: string;
  };
  journal: {
    title: string;
    dek: string;
    read: string;
    related: string;
    cta: string;
  };
  inquire: {
    title: string;
    dek: string;
    prefer: string;
    email: string;
    nextTitle: string;
    next: string[];
    confirm: string;
  };
  thankYou: { title: string; body: string; preview: string; again: string };
  privacy: { title: string; updated: string; sections: { title: string; body: string[] }[] };
  form: {
    steps: [string, string, string];
    next: string;
    back: string;
    submit: string;
    sending: string;
    name: string;
    email: string;
    phone: string;
    service: string;
    services: Record<string, string>;
    date: string;
    dateFrom: string;
    dateTo: string;
    flexible: string;
    place: string;
    people: string;
    peopleOptions: Record<string, string>;
    eventOptions: Record<string, string>;
    days: string;
    dayOptions: Record<string, string>;
    placeType: string;
    placeTypes: Record<string, string>;
    website: string;
    budget: string;
    budgetUnsure: string;
    budgets: Record<string, BudgetOption[]>;
    media: string;
    mediaOptions: Record<string, string>;
    story: string;
    storyPlaceholder: string;
    found: string;
    foundOptions: Record<string, string>;
    language: string;
    languages: Record<string, string>;
    consent: string;
    promoCode: string;
    promoHint: string;
    wish: string;
    wishPlaceholder: string;
    errors: Record<string, string>;
    weddingLimit: string;
    fail: string;
  };
};
